### ISSUE TITLE
Auto Reply Enable

### ISSUE THREAD

**Issue by callumeveratt** [RogerSelwyn/O365-HomeAssistant#101]
Hey,

I've just upgraded to pre-release 4.0.6 as I've been following developments in the auto_reply_enable service in #76

I can't seem to find an o365.auto_reply_enable service within the available services in HA despite it being in the services schema for 4.0.6

Was wondering if I'm being slow, or need to add additional permissions or settings?

**Comment by RogerSelwyn** [comment]
You need to have an email or query sensor to target them at. If you don't have one, then the service isn't created.

https://rogerselwyn.github.io/O365-HomeAssistant/services.html#auto-reply-services

**Comment by callumeveratt** [comment]
Interestingly we have a query sensor at the mo - I'll add an email sensor and see if it makes a difference

**Comment by RogerSelwyn** [comment]
Let me know either way, and I'll check it in the morning. You do also need to set the right permission.

MailboxSettings.ReadWrite - Read and write user mailbox settings

**Comment by RogerSelwyn** [comment]
So you will need to re-authenticate. Just delete or rename the authentication token, and it will prompt you.

**Comment by RogerSelwyn** [comment]
I might add a sensor that shows current settings which is explicitly enabled, then you would get prompted for permissions without having to delete the token. Something for tomorrow.

**Comment by callumeveratt** [comment]
I've just quickly added an inbox sensor now for both the accounts I have registered on the HA instance and no luck on registering the service. In the morning I'll try clearing the auth tokens and re-registering.  Confirmed we have MailboxSettings.ReadWrite on our app registration also.

**Comment by RogerSelwyn** [comment]
Give me to the end of tomorrow and I'll add a new sensor and a new config option to enable, then it will prompt for re-authentication. Watching Ghosts tucked up in bed now, so too late, but I'm chewing it over in my mind.

**Comment by RogerSelwyn** [comment]
> Just need to rm O365-token-cache right?

Not the whole folder, just the token file inside, though I expect it will recreate that anyway.

**Comment by RogerSelwyn** [comment]
Just thought, won't be able to do it tomorrow, I need to get some changes done in a module I don't control. That will probably take a week or so. So, you are best to delete the token.

**Comment by callumeveratt** [comment]
No worries! Sensor sounds like a good idea though.

It does look like a potential reauthentication issue. We already had MailboxSettings.ReadWrite on our app registration previously so I haven't changed anything but the below worked:

1. Delete o365_Cal.token 
2. Restart HA
3. Reauthenticate my email address

That then registered the service, and enabling auto replies worked. My partners however gives the error:

> Failed to call service o365.auto_reply_enable. Not authorisied to update auto reply - requires permission: MailboxSettings.ReadWrite. Got {'type': 'execute_script', 'sequence': [{'service': 'o365.auto_reply_enable', 'data': {'internal_reply': 'Currently away test', 'external_reply': 'Thank you for your email. I will get back to you as soon as possible'}, 'target': {'entity_id': ['sensor.inbox_2']}}], 'id': 131}

I'm guessing because we never used the MailBoxSettings.ReadWrite permission it was never actually activated even though it's always been on the app reg - I'm going to delete her token in a moment and reauthenticate her and I'm assuming it will now work (if I can get something that's signed in as her so I don't get MFA'd!)

Is this a scenario you were expecting with the addition of auto replies, an edge case or something that shouldn't happen at all? I'm guessing it's an MS quirk

**Comment by callumeveratt** [comment]
Didn't get MFA'd and worked as expected, deleted her auth token and reauth'd and now works.

**Comment by RogerSelwyn** [comment]
Not a quirk, but the token sets what you can do. So if you add permissions afterwards it doesn’t matter until you re authenticate and get a new token (you can look in the token file to see the permissions). So I check the permissions before enabling anything (no point having things that will fail anyway) so as to reduce clutter.

**Comment by callumeveratt** [comment]
Yeah I think I'm following you - been a while since I had to properly administer O365 / app reg's. All working now though.

 Do you want me to keep this open re the senor or happy to close?

**Comment by RogerSelwyn** [comment]
Leave it open, then I won't lose it. I've written the PR to the underling module. We'll see how long that takes (he's usually fairly quick), then I'll add the sensor. I won't change 4.0.6 to full release, until I get a new version with the sensor in (probably 4.1.0).

https://github.com/O365/python-o365/pull/920

**Comment by GitHubGoody** [comment]
@RogerSelwyn Is this the issue you mentioned in the v4.0.0b3 release?

"Email and Query sensors are currently broken where the folder config parameter is set. A PR has been submitted to the O365 module to fix."

I use query sensors outside of my Inbox as well. Should I hold off upgrading to v4 until this is resolved?

**Comment by RogerSelwyn** [comment]
No they are fine now. I’m awaiting another change to do with mailbox settings auto reply before doing a full release.

**Comment by RogerSelwyn** [comment]
I would add, there are no bugs I know of on 4.0.7. But because of changes made, I'm doing a slow release of these latest ones so as to catch anything obscure in small numbers.

**Comment by RogerSelwyn** [comment]
Fixed with https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.0.8

Display of current settings to be included in future release
