### ISSUE TITLE
Add documentation for Tasks and new security permissions

### ISSUE THREAD

**Issue by loryanstrant** [RogerSelwyn/O365-HomeAssistant#102]
I've just decided to enable the tasks functionality and so added Tasks.Read (delegated) to my Azure AD App Registration.
Upon HA restart, what I'm seeing in the error logs is:
`Minimum required permissions not granted: ['Tasks.Read', ['Tasks.ReadWrite']]`

It would be nice if Tasks.ReadWrite was not a required permission, so that we could grant read only if we want (like you've accommodated previously for Calendar and other functionality). I know it's using delegated permissions, but bare minimum access is still a preference for many. :-)

**Comment by RogerSelwyn** [comment]
You should be able to just grant Read. But you need to delete the token and re-authenticate. Clearly you won't be able to add/change/delete but you should still be able to read. If that doesn't work, post back and I'll fix it.

**Comment by loryanstrant** [comment]
Hey Roger, I did grant Read initially, however I didn't delete the token and re-auth.
For now I've added ReadWrite, as I'm thinking I might use it as a way to tick off tasks as well.
First challenge is to figure out how to display them cleanly, as the "all_tasks" attribute shows me this:
![image](https://user-images.githubusercontent.com/51473494/210164700-a021a932-b4a4-47cb-ab53-bd4e66cf5a24.png)

Using markdown (borrowed from the To Do integration page) I've managed to at least get it looking nicer:
![image](https://user-images.githubusercontent.com/51473494/210164712-f41022e6-3998-4a70-b26f-66da94bbaaaa.png)

Still need to strip out the "subject" part.

**Comment by RogerSelwyn** [comment]
It’s an array, and can be handled as such. There is some markdown here, but I probably need to work up an example. 

https://github.com/black-roland/homeassistant-microsoft-todo

**Comment by loryanstrant** [comment]
Yeah, that's what I'm using:
```
type: markdown
content: |-
  {% for task in state_attr('sensor.tasks_sc_personal', 'all_tasks') -%}
  - {{ task }}
  {% endfor %}
title: Tasks

```
Which is giving me the second display.
Am curious to know what you're using to display them all in a single card (if you are)?

**Comment by RogerSelwyn** [comment]
I don't use it to be honest, here is some some tweaked markdown to pull out the subject. I'll try to do one with dates/etc in the next while.

```
type: markdown
content: |-
  {% for task in state_attr('sensor.back_primary', 'all_tasks') -%}
  - {{ task['subject'] }}
    {{ task['task_id'] }}

  {% endfor %}
title: To Do
```

**Comment by loryanstrant** [comment]
Thanks! The second task line wasn't required, I ended up going with this:
```
type: markdown
content: |-
  {% for task in state_attr('sensor.tasks_sc_personal', 'all_tasks') -%}
  - {{ task['subject'] }}
  {% endfor %}
title: Tasks
```

And got this:
![image](https://user-images.githubusercontent.com/51473494/210165376-0348a2c9-9e97-480a-8ffc-14db029b4c34.png)

**Comment by RogerSelwyn** [comment]
Documentation added

**Comment by loryanstrant** [comment]
Just FYI for the tasks sensor, I noticed the page shows this:
![image](https://user-images.githubusercontent.com/51473494/210187959-cbbf3728-0bae-4d75-83ad-ba738be44743.png)

But the GitHub version shows this:
![image](https://user-images.githubusercontent.com/51473494/210187962-4b4f4c4c-6098-4285-af1a-8771e2f4dd0f.png)

Not sure if that's a markdown of markdown thing or there's another version that hasn't been published yet.

**Comment by RogerSelwyn** [comment]
Thanks, fixed

**Comment by RogerSelwyn** [comment]
I'll probably tag a few posts, but I'm trying to get some views. I'm considering breaking up the monolithic O365 integration into smaller, more manageable items. If you have a view, please comment here:

[O365 --> MS365 - A potential big change - your views needed](https://github.com/RogerSelwyn/O365-HomeAssistant/discussions/234)
