### ISSUE TITLE
Multiple accounts from the same M365 tenant and HA environment

### ISSUE THREAD

**Issue by loryanstrant** [RogerSelwyn/O365-HomeAssistant#103]
My family all uses M365 (as I get a bunch of free E3/E5 licenses as a MVP), and all have separate accounts in our HA.

There have now been requests to have a HA page show as their browser start page, with a customised dashboard showing their calendar and tasks.

I know we can have multiple M365 tenants in a single HA (as I already use that myself), but is it possible to have multiple users from the same M365 tenant displaying different calendars and tasks in HA?
I suspect the M365 part of it is ok as we're using delegated permissions in Graph.
My thinking is that I _could_ create a separate app registration for each user, but that's not an ideal way to go about it.

Thanks

**Comment by RogerSelwyn** [comment]
I don't think you need another app. I think you just need to add a new account in your config, with the same id/secret. Then when prompted to login, use the relevant credentials (and approve permissions if required), and it will store a different token for the account. I've not actually tried it, but I think it should work. Of course if you want different permissions, you may need a different azure app, but I suspect you know about that better than I do.

**Comment by loryanstrant** [comment]
So, the top two are my existing ones:
![image](https://user-images.githubusercontent.com/51473494/210285728-43208086-b050-41c7-be7e-004feeda3e11.png)

Is your suggestion that just by adding the third one, when my wife logs in to HA it will prompt her to set it up?
If so, I'm thinking that it would also show up when I log in, the key point would be that I should ignore it from my screen.

Also I'm guessing I need to make my wife an admin (at least temporarily) so she can set up the new integration.

Will give it a crack

**Comment by loryanstrant** [comment]
Yep, that did the trick!
Thanks Roger, for this awesome integration!

**Comment by RogerSelwyn** [comment]
I'm glad you have what you want. Not really sure how to present different info to different users in the front-end, I imagine it can be done, by I think that is outside the control of the integration.

**Comment by RogerSelwyn** [comment]
Maybe you can use this to display entity based on user - https://github.com/iantrich/config-template-card
