### ISSUE TITLE
Filter calendar events

### ISSUE THREAD

**Issue by albinmedoc** [RogerSelwyn/O365-HomeAssistant#106]
It would be a nice feature to filter out some events. For example I'm not interested in cancelled events which are prefixed with "Cancelled:".

**Comment by RogerSelwyn** [comment]
Complete with v4.2.0 (still in pre-release). See here for documentation - https://rogerselwyn.github.io/O365-HomeAssistant/calendar_configuration.html

```
    search: "blah"
    exclude:
     - "Cancelled"
     - "Exclude"
```

**Comment by albinmedoc** [comment]
I have now tested the feature and it works great. 
It would be even better if it was case insensitive. 

Another idea is to exclude be regex, this would make it even more flexible.

**Comment by RogerSelwyn** [comment]
> I have now tested the feature and it works great. It would be even better if it was case insensitive.
> 
> Another idea is to exclude be regex, this would make it even more flexible.

And done with v4.2.1 - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.2.1

**Comment by albinmedoc** [comment]
Wow, incredible work!
Nice job!
