### ISSUE TITLE
latest release is pinned to 4.0.3

### ISSUE THREAD

**Issue by akshaya-a** [RogerSelwyn/O365-HomeAssistant#107]
Just wanted to drop a quick note that by switching to a "pre-release" style github release HACS doesn't by default show the updates as ready for consumption unless the user is aware and opts into "show beta versions" in the redownload menu. I wasn't sure if this was intentional so thought I'd note it here 😄

**Comment by RogerSelwyn** [comment]
Yes I know, I'm just leaving them in that state until I prepared to go to a full release. I was waiting on an underlying code release but it seems to be taking a while, so I've done a workaround which I will duly release soon.
