### ISSUE TITLE
Updating o365 sensor took longer than the scheduled update interval

### ISSUE THREAD

**Issue by sarahmva** [RogerSelwyn/O365-HomeAssistant#108]
I am getting this error every 30 seconds in my logs. I tried to find a way to set the update interval but did not find a parameter for it. Is there anything else I can check?

Thanks!

Versions: 
O365 integration: 4.0.3
HA: 2023.1.2

Config:

o365:
  accounts:
    - account_name: O365
      client_id: "[***]"
      client_secret: "[***]"
      alt_auth_method: False
      enable_update: True
      track_new_calendar: True
      email_sensor:
        - name: o365_FCPS
          max_items: 10
          is_unread: True
          folder: "Inbox/FCPS"
      query_sensors:
        - name: "o365_inbox_query"
          folder: "Inbox" #Default is Inbox
          from: "[***]"
          subject_contains: "HA Command"
          has_attachment: True
          max_items: 2
          is_unread: True
      status_sensors: # Cannot be used for personal accounts
        - name: "o365_teams_status"
      chat_sensors: # Cannot be used for personal accounts
        - name: "o365_chat"

**Comment by RogerSelwyn** [comment]
There is no way to set the interval. If you want help with the error, please post it here. Please also use the <> icon in the toolbar to enable proper formatting of any code you post.

**Comment by RogerSelwyn** [comment]
Looking at this again, occasionally the o365 seems slow to respond. Sorry I have no magic other than to say make the query less complex. Sorry, I see no way of improving the performance of an MS provided api. I usually find restarting the HA instance makes it go away, or make sure the attachments you are downloading are not of any size.
