### ISSUE TITLE
how do I get to 'api permissons'?

### ISSUE THREAD

**Issue by jurgenweber** [RogerSelwyn/O365-HomeAssistant#116]
https://rogerselwyn.github.io/O365-HomeAssistant/permissions.html

Would really love to do this, but where do I go? I can not find 'api permissons', I am not really a MS persion so some further detail on how to setup the permission on the o365 would be great.

**Comment by RogerSelwyn** [comment]
Have you followed the instructions on this page including setting up an Azure App?

https://rogerselwyn.github.io/O365-HomeAssistant/prerequisites.html
