### ISSUE TITLE
Auto reply multiline replies

### ISSUE THREAD

**Issue by lodesmets** [RogerSelwyn/O365-HomeAssistant#118]
Hey,

I wanted to set my auto reply to contain multiple lines, but everytime I test it, the result is a single line text in outlook.

I also tried the YAML mode of the service with this: https://yaml-multiline.info/

I'm using version 4.1.2

**Comment by RogerSelwyn** [comment]
If you can provide some of the input you are trying to set it to, and I'll see what is achievable. May take a backend change, which can take a while.

**Comment by RogerSelwyn** [comment]
OK, so I can see what it is doing, it is removing line breaks at the back-end. I'll have to see if it can be fixed. May take a while.

**Comment by lodesmets** [comment]
Damn, you really respond fast. Thanks for the responses

**Comment by RogerSelwyn** [comment]
Depends if I’m in front of my Mac or not 😀. Or sat bored in the car as now.

**Comment by RogerSelwyn** [comment]
Sorry, was having some me time doing some Floorplan stuff. Quite absorbing.

In any case, I just had some time to loom at this. It is possible to create a multi-line reply, you just need to format it correctly.... Easier said than done. The integration just passes through what you enter and that gets configured on MS365. But of course you need to pass through the right thing. So what I did was to set it up in Outlook, and then look via the MS Graph Rest API explorer to see what gets configured.

The explorer can be found here - https://developer.microsoft.com/en-us/graph/graph-explorer. The relevant end point to query is this one - https://graph.microsoft.com/v1.0/me/mailboxSettings. You will likely have to give yourself permission to run the query, but it should lead you through that.

You will see something like this gets configured.

`<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01//EN\" \"http://www.w3.org/TR/html4/strict.dtd\"><html><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta http-equiv=\"Content-Style-Type\" content=\"text/css\"><title></title><meta name=\"Generator\" content=\"Cocoa HTML Writer\"><meta name=\"CocoaVersion\" content=\"2299.4\"><style type=\"text/css\">p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Times; -webkit-text-stroke: #000000}p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Times; -webkit-text-stroke: #000000; min-height: 14.0px}span.s1 {font-kerning: none}</style></head><body><p class=\"p1\"><span class=\"s1\">Multiline response</span></p><p class=\"p2\"><span class=\"s1\"></span><br></p><p class=\"p1\"><span class=\"s1\">This is line 2</span></p></body></html>`

Bear in mind that in this all the double quotes have been escaped with a backslash. So if you take out the backslashes, and put that into the service call to set the auto-reply, it should work.

Now I could start trying to build that based on somebody providing a multi-line response, but I think that may be fraught with horror somewhere along the way.

Shout if you have any questions.

**Comment by lodesmets** [comment]
Thanks for the response, I tested it, and it indeed works with the HTML markup.

I didn't have to do the whole css stuff. Just adding <br> was enough
