### ISSUE TITLE
Calendar Entities not showing

### ISSUE THREAD

**Issue by cgms** [RogerSelwyn/O365-HomeAssistant#120]
I've managed to get the integration working and email inbox sensor is showing count etc. I have the calendar yaml setup as bellow, but no calendar entities are showing up, Any idea what I'm doing wrong? How do I get the entities to exist?

- cal_id: !SECRET
  entities:
    - device_id: Calendar
      end_offset: 24
      name: Calendar
      start_offset: 0
      track: true

**Comment by RogerSelwyn** [comment]
Any errors sharing in your logs?

**Comment by cgms** [comment]
Only warnings
2023-02-08 14:58:30.270 WARNING (MainThread) [custom_components.o365.utils] Could not locate token at /config/o365_storage/.O365-token-cache/o365_outlook.token
2023-02-08 14:58:30.324 WARNING (MainThread) [custom_components.o365] No token, or token doesn't have all required permissions; requesting authorization for account: outlook

**Comment by RogerSelwyn** [comment]
And I assume that is the autogenerated yaml which you have not modified? Have you rebooted HA again?

**Comment by RogerSelwyn** [comment]
Please post your O365 config minus secrets

**Comment by cgms** [comment]
o365:
  accounts:
    - account_name: outlook
      client_id: !SECRET
      client_secret: !SECRET
      alt_auth_method: False
      enable_update: True
      email_sensor:
        - name: inbox
          max_items: 2
          is_unread: True
          download_attachments: False
      query_sensors:
        - name: "Email"
          folder: "Inbox" #Default is Inbox
          from: "chris@cmsdes.co.uk"
          subject_contains: "*"
          has_attachment: True
          max_items: 2
          is_unread: True
      todo_sensors:
        enabled: False

yes, autogenerated calendar, just changed the names

**Comment by RogerSelwyn** [comment]
Please format the config correctly using the <> in the GitHub editor toolbar.

**Comment by cgms** [comment]
yes, and email count increments etc properly on the email sensor

**Comment by RogerSelwyn** [comment]
Then the implication is you haven’t set the permissions correctly if you are getting that error. Just about to have physio, so will look at the code more later.

**Comment by RogerSelwyn** [comment]
Please do a HA restart and post all messages from the logs (that come from o365).  I don’t think you should get just that one error.

**Comment by cgms** [comment]
ok, thanks, will check the API perms as well

**Comment by RogerSelwyn** [comment]
You should have an authentication request if you have that warning.

**Comment by cgms** [comment]
I only got the below warning, and it looks like it is working now, so happy days!

```
2023-02-08 15:27:31.616 WARNING (MainThread) [homeassistant.components.calendar] Setup of calendar platform o365 is taking over 10 seconds.
```
