### ISSUE TITLE
See Completed tasks ?

### ISSUE THREAD

**Issue by B-Hartley** [RogerSelwyn/O365-HomeAssistant#122]
I want to be able to delete tasks that are no longer required, even if they are completed.
I could store the taskID for later.

But if there was a way of accessing completed tasks, it could be helpful ?

is it practical ?

**Comment by RogerSelwyn** [comment]
I'm away at the moment, I'd need to just work that through, but I think it should be feasible.

**Comment by B-Hartley** [comment]
Thanks.
In a dream world, when a task was clicked as completed, it would trigger an event into home assistant.  But I guess I'm asking too much now !

**Comment by RogerSelwyn** [comment]
Never triggered events in HA, but I can certainly look and see if I can learn something new.

**Comment by RogerSelwyn** [comment]
Just working up to doing this. Basically I'll have to add a poll for completed items (I think it does it on 10 seconds, but not 100% sure). Can't do it so it is instantaneous, because that would required a webhook url on the HA instance, and all the challenges required of getting people to configure an internet accessible HA instance, etc.

Are you wanting display of completed items, or just the event so you can trigger delete?

**Comment by B-Hartley** [comment]
Ideally I’d get a list of all tasks instead of just open tasks.
Then complete or not would be an attribute.

If that’s not possible then just an event that told me a task had been ticked would be fine.
A delay before that happens is fine.

Bruce Hartley
Click Spares
07966 924863

________________________________

**Comment by RogerSelwyn** [comment]
Completed with - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.2.3

See here for config details - https://rogerselwyn.github.io/O365-HomeAssistant/tasks_configuration.html and here for events - https://rogerselwyn.github.io/O365-HomeAssistant/events.html

**Comment by B-Hartley** [comment]
I've got a task that was completed and deleted from the app.
It is still showing in home assistant as a "completed task".
I've done a home assistant restart, it still shows ?

I executed the service to delete it and it went away, but it didn't exist in the app even before I did that?

thoughts ?

**Comment by RogerSelwyn** [comment]
I’ll take a look and see if a delete from an external app actually deletes it. What so are you using? I use Reminders on iPhone but there are plenty of other ways.

**Comment by B-Hartley** [comment]
I'm using the microsoft todo app.
previously it did delete it.
I'm wondering if it is a timing issue?

**Comment by B-Hartley** [comment]
I'll have an experiment tomorrow.

**Comment by RogerSelwyn** [comment]
Bear in mind before I wasn’t showing completed items, so it might appear ‘deleted’ but actually be completed. I’ll take a look tomorrow on what happens when an item is deleted.

**Comment by B-Hartley** [comment]
I'm having problems reproducing this problem.
So happy to put it down to weirdness for now.  I'll let you know if I see it happen again.

**Comment by RogerSelwyn** [comment]
I just tried as well, using To Do for Mac. As far as I can see deleting something int To Do, deletes it from MS 365, so it should not be able to be retrieved. I'd do a cache clear (Cmd/Shift/R) in your browser. I do sometimes find I need to do that to get sensors to show properly even after a restart. As you can imagine in Dev I'm restarting very often....
