### ISSUE TITLE
Ability to grab email_sensor with HTML output

### ISSUE THREAD

**Issue by micky2171** [RogerSelwyn/O365-HomeAssistant#123]
It would be really handy to have a HTML output in the email_sensor instead of the stripped one.
I can't see anything in the documentation for this so I'm guessing it doesn't exist?

![image](https://user-images.githubusercontent.com/7550213/220891106-4ade3250-5ff8-4271-8b12-66228e16b002.png)

**Comment by RogerSelwyn** [comment]
On pre-release - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.2.4

Use html_body to configure - https://rogerselwyn.github.io/O365-HomeAssistant/installation_and_configuration.html
