### ISSUE TITLE
Access the Outlook "family" calendar

### ISSUE THREAD

**Issue by kalhimeo** [RogerSelwyn/O365-HomeAssistant#124]
Hi,

Thanks for the great integration! I try to figure out how to access the Outlook family calendar (this calendar is automatically created by MS when you create a family and is shared between all family members).

I believe that this calendar belongs to a "Group" but I can't retrieve any group ID when I use "https://graph.microsoft.com/v1.0/me/transitiveMemberOf/microsoft.graph.group" in Graph :

```
{
    "error": {
        "code": "UnknownError",
        "message": "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\"><head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"/><title>404 - File or directory not found.</title><style type=\"text/css\"><!--body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}fieldset{padding:0 15px 10px 15px;} h1{font-size:2.4em;margin:0;color:#FFF;}h2{font-size:1.7em;margin:0;color:#CC0000;} h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:\"trebuchet MS\", Verdana, sans-serif;color:#FFF;background-color:#555555;}#content{margin:0 0 0 2%;position:relative;}.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}--></style></head><body><div id=\"header\"><h1>Server Error</h1></div><div id=\"content\"> <div class=\"content-container\"><fieldset>  <h2>404 - File or directory not found.</h2>  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3> </fieldset></div></div></body></html>",
        "innerError": {
            "date": "2023-02-27T08:07:41",
            "request-id": "5ab72e50-26c5-4737-9520-01838e1d20c5",
            "client-request-id": "3a356e3d-c800-9721-90f9-f056c4fb46e9"
        }
    }
}
```

Any idea ?

Best regards,
Laurent

**Comment by RogerSelwyn** [comment]
I get this same error (when I managed to connect with my personal MS account, rather than my MS365 Tenant account). When I connect with my MS365 Tenant the url works fine, but doesn't show a Family calendar (yes I have tried creating one).

I have no idea where the family calendar is created, because equally I can't see it under shared calendars.

Sorry, no idea. If you figure it out, I can see if it is feasible to add.

**Comment by kalhimeo** [comment]
Thanks for the informations, hopefully this gets a better integration from MS in the future. I will let you know if I hear about something ;-)

**Comment by akshaya-a** [comment]
@kalhimeo I don't know if this helps, but I didn't do anything special and the "Your Family" calendar shows up for me using this integration:

![image](https://user-images.githubusercontent.com/16749003/227040769-f0ec686e-9c29-47f0-bb1a-cb5e6dcbdc29.png)

![image](https://user-images.githubusercontent.com/16749003/227040997-60e3a91c-aeb7-4415-a0f5-7bacf5d0bf26.png)

config/o365_storage/o365_calendars_AK Personal.yaml
![image](https://user-images.githubusercontent.com/16749003/227041148-f63d6085-b9a3-44bc-9b0a-a218d07ec940.png)

**Comment by kalhimeo** [comment]
Thank you so much for your message, indeed it now appears for me too ! Looks like MS or O365 did some update :-)
