### ISSUE TITLE
Can't get authentication working using MFA. 

### ISSUE THREAD

**Issue by xljuol** [RogerSelwyn/O365-HomeAssistant#126]
When linking my account to o365 the pasted redirect uri is not accepted. Getting Error. I've added both redirects URI to Azure APP.

**Comment by RogerSelwyn** [comment]
Please post as much detail as you can and make sure you have followed the steps exactly. Ensure you include the error you get in the details you provide.

**Comment by xljuol** [comment]
Yep - I'm a bit new to HA. Where can I find any relevant logs? I've followed the steps exactly and have a feeling what we try to achive. In the archived o365 I where to enable ID tokens for implicit and hybrids flows. This is now requiered any more?  This is what I found in the log:
![image](https://user-images.githubusercontent.com/32161531/224568452-d5a5538a-de54-4f1f-918b-dc9f66b65085.png)
 Thx

**Comment by RogerSelwyn** [comment]
> In the archived o365 I where to enable ID tokens for implicit and hybrids flows.

Sorry don’t know what you mean by this. I’m guessing English isn’t you first language, just expand on what you are trying to say and I’ll probably figure it out. 

You have found the logs where any errors from the integration would be posted. You said ‘Getting error’ in your original post, what is the error?

**Comment by xljuol** [comment]
Thats allright! This checkbox was enabled in the archived version of o365 integration.
![image](https://user-images.githubusercontent.com/32161531/224571725-d34d1d4e-607b-4dc1-b429-1767c2abb401.png)
 Checkbox ID tokens

The error I get inte the GUI is:
Error while authenticating, please see logs for more info.

I've done the linking but the redirect URI get me the error. I've also added MFA URI into the azure APP authentication config.

I've located the cal_id using graph explorer som the I'm confident this is correct. I've tripple checked Application ID and secret ID.

Cheers

**Comment by RogerSelwyn** [comment]
> This checkbox was enabled in the archived version of o365 integration.
> ![image](https://user-images.githubusercontent.com/32161531/224571725-d34d1d4e-607b-4dc1-b429-1767c2abb401.png)
> Checkbox ID tokens

This is not part of this integration as far as I know. 

Please can you post a copy of tied configuration with secrets redacted.

**Comment by xljuol** [comment]
yep

Configuration.yaml
# O365 Integration
o365:
  accounts:
    - account_name: ljuol@outlook.com
      client_id: "xxxxx"
      client_secret: "xxxxx"
      alt_auth_method: False
      enable_update: True
      email_sensor:
        - name: inbox
          max_items: 2
          is_unread: True
          download_attachments: False
      query_sensors:
        - name: "O365 - Ola"
          folder: "Inbox/Test_Inbox" #Default is Inbox
          from: "ola@ljungkrona.se"
          subject_contains: "Example subject"
          has_attachment: True
          max_items: 2
          is_unread: True
      status_sensors: # Cannot be used for personal accounts
        - name: "User Teams Status"
      chat_sensors: # Cannot be used for personal accounts
        - name: "User Chat"
      todo_sensors:
        enabled: False

o365_calendars_ljuol@outlook.com.yaml
- cal_id: Axxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  entities:
  - device_id: family_calendar
    end_offset: 24
    name: Familjekalender
    start_offset: 0
    track: true

**Comment by RogerSelwyn** [comment]
I’d be pretty sure you using an email address as an account name will cause an error. The account name is just a name, not the email address associated with the account (that is handled by the authentication predicted and token provided).  

If that doesn’t work I’d suggest setting this up with just the basic config as a starting point. So no Inboxes or the status/chat sensors. Make sure that works first. I would delete the azure application and follow the instructions carefully. (The implicit/hybrid stuff, I’m not sure where you got that from, it is not in the instructions so is irrelevant if you are following them). 

As a suggestion, when posting config, always better to format using the <> in the GitHub toolbar, because then any formatting is shown properly.

**Comment by xljuol** [comment]
This is now what is left.

Thx!

`# O365 Integration
o365:
  accounts:
    - account_name: Ola Ljungkrona
      client_id: "xxxxxxxx"
      client_secret: "xxxxx"
      alt_auth_method: False
      enable_update: True

o365_calendars_ljuol@outlook.com.yaml

- cal_id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  entities:
  - device_id: family_calendar
    end_offset: 24
    name: Familjekalender
    start_offset: 0
    track: true
     
`

**Comment by RogerSelwyn** [comment]
Please remove spaces from the account name, it is used as part of file names. 

As noted in bullet 2 of point 4 of the [instructions here](https://rogerselwyn.github.io/O365-HomeAssistant/installation_and_configuration.html) you do not need to manually create the calendars.yaml, it will get created automatically after authentication and is the wrong name anyway.

As stated above, please go back and follow the instructions. I have added a note not to use email address or spaces in the account name.

**Comment by xljuol** [comment]
Hi,

I've redone the entire configuration an still get the same error:
![image](https://user-images.githubusercontent.com/32161531/224781556-80b8a62b-0237-432f-9883-0be59fa10177.png)

I'm getting the challange when linking the account and have to grant access using MFA as supposed. I'm also getting the oauth2 permissions request when linking and pasting the returend URL. 

Yaml now looks:
``
o365:
  accounts:
    - account_name: ola-at-ljungkrona
      client_id: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      client_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      alt_auth_method: False
      enable_update: True

Files are copied to config/custom_components/o365 using HACS package

Error:
`2023-03-13 18:26:58.410 ERROR (SyncWorker_4) [O365.connection] Unable to fetch auth token. Error: (invalid_client) AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'`

I've copied the secret ID from azure portal

Cheers

BTW the documentation is very good - just have to read a couple odf times..

Thx
Ola

**Comment by xljuol** [comment]
ah....

**Comment by RogerSelwyn** [comment]
> You need the secret value not the secret id.

Point 5 of the pre-requisite instructions, and it tells you that in the error message you got 😉

**Comment by xljuol** [comment]
See it now! Sorry

**Comment by xljuol** [comment]
Works fine now! Thx!
