### ISSUE TITLE
Seteting completed status from service ?

### ISSUE THREAD

**Issue by B-Hartley** [RogerSelwyn/O365-HomeAssistant#133]
Is it possible to add the ability to set the completed status of a task from the update_task service?
Would be potentially useful.

Thanks

**Comment by RogerSelwyn** [comment]
Not currently, but I’ll look into adding it.

**Comment by RogerSelwyn** [comment]
Completed with - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.2.10
