### ISSUE TITLE
O365 could not be set up after Update - extra keys not allowed @ data['accounts'][0]['alt_auth_flow']

### ISSUE THREAD

**Issue by Competizione** [RogerSelwyn/O365-HomeAssistant#134]
After update from 3.3.0 to any higher Version its not starting any more.
Config was allready the newer version with accounts.
Tried default and alternative authentication methode, same behavior.
Tried different HA Versions (now 2023.3.6), in vain.
After Downgrade to 3.3.0 its ok.

Config:
o365:
  accounts:
    - account_name: Name
      client_secret: !secret O365_client_secret
      client_id: !secret O365_client_id
      alt_auth_flow: False
      track_new_calendar: True
      enable_update: True
      email_sensor:
        - name: inbox
          max_items: 2
          is_unread: True
          download_attachments: False
      query_sensors:
           ...

Logger: homeassistant.setup
Source: custom_components/o365/__init__.py:58
Integration: Office 365 Calendar (documentation, issues)
First occurred: 15:57:04 (1 occurrences)
Last logged: 15:57:04

Error during setup of component o365
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 256, in _async_setup_component
    result = await task
  File "/config/custom_components/o365/__init__.py", line 58, in async_setup
    accounts = MULTI_ACCOUNT_SCHEMA(conf)[CONF_ACCOUNTS]
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['accounts'][0]['alt_auth_flow']

**Comment by RogerSelwyn** [comment]
Please take note of the release notes in 4.0.1 - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.0.1

alt_auth_flow has been replaced by alt_auth_method.

**Comment by Competizione** [comment]
Oh yeah, precise reading helps...I didn´t recognized the _method at the end as difference.
Sorry, guess one coffee will not be enough 😂

**Comment by RogerSelwyn** [comment]
😀 No problem 😀
