### ISSUE TITLE
o365.new_task not recognised as a valid service

### ISSUE THREAD

**Issue by wigster** [RogerSelwyn/O365-HomeAssistant#135]
All of a sudden, in HA 2023.04, the repair wizard is complaining that o365.new_task is not a valid service 

```
The automation "Notify: Clean Devices TODO" (automation.notify_clean_devices) has an action that calls an unknown service: o365.new_task.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.
```
This is the bit of the automation which caused this:
```
          - service: o365.new_task
            data:
              subject: Run dishwasher cleaning cycle
              due: "{{now().date()+timedelta(days=1)}}"
              reminder: |-
                {% if now()<today_at('19:00') %}
                  {{today_at('19:00')}}
                {%else%}
                  {{today_at('19:00')+timedelta(days=1)}}
                {%endif%}
            target:
              entity_id: sensor.house_to_do_o365_name
```
and indeed trying to create a new task in dev tools/services reports that o365.new_task is not a known service.

`sensor.house_to_do_o365_name` is available and populated properly.

**Comment by RogerSelwyn** [comment]
I assume you have also upgraded to o365 4.2.9 or higher. Did you read about the breaking change in there?

https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.2.9

**Comment by the-smart-home-maker** [comment]
> I assume you have also upgraded to o365 4.2.9 or higher. Did you read about the breaking change in there?
> 
> https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.2.9

Very good to know! I was banging my head around this. Could not understand why I won't see the tasks services. I think it would be very good to include the attribute `enable_update` in the tasks section in the example YAML config in your documentation.
