### ISSUE TITLE
gkeepapi.exception.LoginException: ('BadAuthentication', None)

### ISSUE THREAD

**Issue by biejay** [RogerSelwyn/O365-HomeAssistant#141]
I got the error message "gkeepapi.exception.LoginException: ('BadAuthentication', None)" since my latest reboot.
Tried to: 
> delete the token
> created a new client secret
> changed "please set ‘alt_auth_method’ to True" but this gave me an error on the azure portale (wrong URI or sth.)

Was there an update of this addon or the azure portale ? The addon worked the last 2-3 month or so.

**Comment by RogerSelwyn** [comment]
Please post the full error. gkeepapi is related to Google Keep - https://gkeepapi.readthedocs.io/en/latest/ - which is not related to the O365 integration

**Comment by biejay** [comment]
Oh yes, sorry. I am completely lost right now. I combined both addons and gut confused. But thanks for the fast reply anyway!
