### ISSUE TITLE
Format of start and end attributes for all_day events

### ISSUE THREAD

**Issue by steveisaguy** [RogerSelwyn/O365-HomeAssistant#142]
Hey,
Thanks for this add-on. Its great and really valuable.
I am using a template to parse the data in each calendar attribute in order to find upcoming events etc.
However after updating to the most recent version I am having an issue that events that are "all_day" have a start and end attribute in the datetime.date format, where as before this was in the datetime.datetime format.

The impact is that my template now needs a check to see what format the start attribute is.

Are you able to update the attribute back to the previous format?
Hope this makes sense and isnt too hard. Thanks

This is what it is now:
- summary: test event
  start: '2023-05-18'
  end: '2023-05-19'
  all_day: true
  description: ''
  location: ''
  categories: []
  sensitivity: Normal
  show_as: Free
  attendees: []

However I am sure previously the format was:
- summary: test event
  start: '2023-05-18T14:15:00+00:00'
  end: '2023-05-18T15:30:00+00:00'
  all_day: true
  description: ''
  location: ''
  categories: []
  sensitivity: Normal
  show_as: Busy
  attendees: []

**Comment by RogerSelwyn** [comment]
Sorry, no. HA Core requires them to be as a Date to be properly recognised as an all day event. And in actual fact (if I remember correctly) this is what other systems such as Google Calendar user as well, so it is better to be consistent. I think also Microsoft do the same thing. Not in front of a PC now so can’t check, but pretty sure that is the case.

**Comment by steveisaguy** [comment]
Cool, good to know in which case I will update the template instead.
Thanks for the quick response!
