### ISSUE TITLE
Todo card?

### ISSUE THREAD

**Issue by los7702** [RogerSelwyn/O365-HomeAssistant#144]
Im not sure but wouldn't it be great wit a card that rendered checkboxes for the tasks, implementing the services Update, Complete and maybe even new Task?
I have no Idea of how to do, but something like the Shoppinglist is what I'm talking about. 

//Lasse

**Comment by RogerSelwyn** [comment]
Sorry, this isn’t question for the integration which is backend only. A card would be frontend coding which I don’t do and would not reside in this repository. I’m happy to provide a link to a card that someone created, or include an example using existing card types such as the Entities card.

**Comment by los7702** [comment]
Ahh that seems obvious when you explin it that way. Please all links are welcome :-)

**Comment by RogerSelwyn** [comment]
The bottom of this page shows how to use Markdown to create a list from the output I create. Not sure if you can add checkboxes and service calls as well - https://github.com/black-roland/homeassistant-microsoft-todo

**Comment by fixtse** [comment]
Hey, I created a custom card for the integration, https://github.com/fixtse/o365-card.
Currently, it only provides an easy way to present the data from the sensors in the dashboard, I hope it helps 😁
