### ISSUE TITLE
ToDo not available as an API permission anymore?

### ISSUE THREAD

**Issue by chimph** [RogerSelwyn/O365-HomeAssistant#147]
![Screenshot 2023-06-07 105216](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/76972906/4ee9947f-2351-4747-9ec3-4fca5f4b37a5)

**Comment by RogerSelwyn** [comment]
Sorry, I'm not sure what that is a screenshot of. Please explain what you are trying to do and where you are stuck.

**Comment by RogerSelwyn** [comment]
Did you look for Tasks?

**Comment by chimph** [comment]
Apologies. Yes I see now I need to change 'Task' permissions and that there isnt a 'Todo' permission to change. Thank you
