### ISSUE TITLE
Minimum permission not granted for account

### ISSUE THREAD

**Issue by PrinceAli0** [RogerSelwyn/O365-HomeAssistant#150]
Hey all,

Been using this wonderful HACS add-on for Home Assistant since it was PTSC and moved to the fork that RogerSelwyn has taken up supporting.  Before anything I want to express my thanks for your ongoing effort.

In the last week, I noticed that my Calendars were not loading in HA and after digging into the HA logs, it was due to the need to re-authenticate (my Microsoft App Client Secret expired a week ago).  No biggie, read the O365 documentation, deleted the _<config>/o365_storage/.O365-token-cache_ file, rebooted the HA host, re-authenticated (approved the Microsoft permissions approval), and copied/pasted the return URL from the browser.  However, I get the following error:

![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/65803023/f8a54318-4639-4ef0-b78b-6844f34ed02c)

Decided to wipe and recreate the setup using the instructions.  This included removing the Microsoft App Registration, the O365 add-on from HACS, deleted the associated files, remove the entry for my Configuration.YAML file, and rebooted multiple times.  I even went so far as to verify my domain for Microsoft using the whole _/.well-known/microsoft-identity-association.json_ file placed on a reachable location on my public DNS entry.  Once all that was done, I recreated the entire setup using the instructions (100%, didn't deviate).  However, the outcome is still the same as above. 

**Configuration.YAML**:

![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/65803023/63a2dbb0-eafd-4511-8169-c0f75e1d2ec6)

**Microsoft API Configuration**:

![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/65803023/738915a6-ad42-4a8e-8759-b8f535569f96)

Any help would be greatly appreciated.  I use this wonderful add-on on the main Dashboard of my family hub to quickly display our schedule for the day.

Thanks!

**Comment by RogerSelwyn** [comment]
An immediate work around is to remove the status and chat sensors from your config. You will see that it tells you it is missing those permissions above the error. My suspicion is that you have added those sensors but you are using a personal account (like hotmail.com or outlook.com).

If you look in the token file, you will see what permissions that O365 believes you can have (which can be different to what you have granted in Azure app, it won't give your presence or chat for a personal account).

If it is granting you those permissions, then it is a bug. Post back the list of permissions from your token file (do not post the token!!).

**Comment by RogerSelwyn** [comment]
See last error - https://rogerselwyn.github.io/O365-HomeAssistant/errors.html

**Comment by RogerSelwyn** [comment]
I'd be interested to know what error showed up when the client secret expired, because then I can add appropriate guidance. Just deleting the token won't sort it, it will need a new client secret adding to the Azure App.

**Comment by PrinceAli0** [comment]
Roger,

A snip of what is in the token file:

![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/65803023/74f1635f-f5d1-4860-ac36-52da8e289ecf)

As you suggested, it appears that Microsoft isn't passing it to the client...this is is a personal account.  Apparently, I didn't read as accurately as I suggested......<SIGH>.  

I've gone ahead ahead and (1) removed the sections for Chat/Presence from the Configuration.YAML and (2) updated the AzureApp to not include those items (Presence.Read, Chat.Read).  Fully restarted HomeAssistant and I'm waiting ~5-10 mins before I try again.

As for the original error, I didn't save it/copy the info so I don't have it available.  If this works in like ~10 mins, I have no problem deleting the whole thing (HA/Azure), setting up a new AzureApp with a client for the lowest date threshold and getting the detail back to you from the client/logs.

Thanks!

**Comment by PrinceAli0** [comment]
Worked perfectly.  Tomorrow I'll wipe it all, recreate it with a short-lived client secret and report back the error that shows when it just expires on its own (both in the UI and in logs).

Thanks!

**Comment by RogerSelwyn** [comment]
I've set up a custom secret for myself that expires tomorrow, so I can see if it can be captured. In setting ti up, no need to delete the token, just create the secret, add to your config and reboot.

**Comment by RogerSelwyn** [comment]
Fixed with - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.3.3
