### ISSUE TITLE
Feature: Get only basic calendar information (meeting titles and times)

### ISSUE THREAD

**Issue by Vitani** [RogerSelwyn/O365-HomeAssistant#158]
I'd like to use this integration with my work calendar, but my employer are (understandably) very restrictive on what information is allowed outside of the O365 bubble. They have said that the `Calendars.ReadBasic` permission **would** be acceptable, but the `Calendars.Read` permission used by the integration is not.

Would it be possible to have a `basic` option added to the config, which uses the more restrictive permission?

**Comment by RogerSelwyn** [comment]
I'm adding the support using config param `basic_calendar`. It will request:

- offline_access
- user.Read
- calendar.ReadBasic

**Comment by RogerSelwyn** [comment]
Please try this release - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.4.0b1

**Comment by Vitani** [comment]
I tried `v4.4.0b3`, and after IT approved my Azure app it worked as expected

![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/5907401/11115405-a5a7-48cb-80ca-b886766061fa)
