### ISSUE TITLE
Second Account within the Same Microsoft Tenant?

### ISSUE THREAD

**Issue by InnercircleDesign** [RogerSelwyn/O365-HomeAssistant#159]
I'm not sure if I missed something here but is it possible to pull another users calendars and tasks from the same Microsoft tenant?
Also how would I be able to show both calendars in a overlay?

**Comment by RogerSelwyn** [comment]
You can either:

- have the second user grant access to their calendars (pretty sure I’ve tried this and it works) they will then be available through the first users normal config. 
- setup a second account in config.yaml (you can use the same client id and secret) and login with the second users credentials when prompted for the repair. I know this works for sure. 

Not sure what you mean by shows them in an overlay. Note that the integration does not do display, it just provides data for the HA Lovelace frontend to present.
