### ISSUE TITLE
Tasks - Read Assignments from MS To Do

### ISSUE THREAD

**Issue by Caff522** [RogerSelwyn/O365-HomeAssistant#165]
Hi,

Many thanks for your work on this.

In my use case, certain tasks (chores) are assigned to individuals within MS To Do. It would be very helpful to have the tasks sensor reflect such assignments. Is this something that would be feasible to implement?

Regardless, thanks again!

**Comment by RogerSelwyn** [comment]
Thanks for submitting this request.

I think assignments only work for shared ToDo lists, and I don't think the integration supports shared ToDo lists. Are you able to access a shared list? If so, let me know how, and I'll figure out whether it can be done.

**Comment by Caff522** [comment]
Thank you. I don't seem to have any issues accessing a shared list. I created a list in MS To Do and invited others to it. It shows up as "sensor.chores_[my account name]", but the sensor displays tasks created by others just fine. Tasks within that list can be assigned to the invited individuals in MS To Do.

Apologies if the above isn't clear; happy to provide any additional information.

**Comment by RogerSelwyn** [comment]
I'll take a look.

**Comment by RogerSelwyn** [comment]
From what I can see in the MS Graph API, this isn't possible at the moment. I can see a List is shared, but I can't see who it is shared to, or that an individual task is assigned to anyone.

This query here also suggests the same:-
https://stackoverflow.com/questions/76424128/how-to-get-todo-task-list-sharings-and-task-groups-from-exchange-with-ews

**Comment by Caff522** [comment]
Thank you for looking into it.
