### ISSUE TITLE
Token retrieval error.

### ISSUE THREAD

**Issue by nickpieters** [RogerSelwyn/O365-HomeAssistant#167]
Hi

I'm on the last step to connect to Azure, HA config went fine but when i submit the return url i get the following error:
Token file retrieval error, check log for errors from O365.

Any pointers where i can start to look what went wrong? I don't think i already have received a token yet.

Thanks!

**Comment by RogerSelwyn** [comment]
Did you look in the log for errors as suggested?

**Comment by nickpieters** [comment]
Thanks for the quick response, I'd was indeed my mistake: copy/paste issue.
Feel a bit dumb, but it's solved now :)
