### ISSUE TITLE
Calendar does not update after removing event

### ISSUE THREAD

**Issue by krafcik02** [RogerSelwyn/O365-HomeAssistant#168]
Hi, I am experiencing a bug, that happens after delete current or upcoming event in calendar, the entity state (also attributes) is not updated.

VERSIONS
------------
Home Assistant 2023.10.0
Supervisor 2023.10.0
Operating System 10.5
Frontend 20231002.0 - latest

**Comment by RogerSelwyn** [comment]
I have found a bug in there if you delete the last event in the configured date range. Just figuring out what to do about it.

**Comment by krafcik02** [comment]
1. In **Calendar** menu I create an event, into my Calendar from o365, that will start at **13:30** (**Current time is 13:02**) and ends at **14:00**.
2. I Update the calendar entity (my Calendar from o365) from **Services** menu from developer tools, using Service **Home Assistant Core Integration: Update entity** and as **Target** I choose my **Calendar entity** to see if there is my newly created event. I see the created event here. 
3. Then in **Calendar** I choose the event and then I remove it. 
4. I wait for 30 seconds and check if **Entity state** changes and the event is removed from the Entity state. But it is not.
5. I Update the calendar entity (my linked Calendar from o365) from **Services** using Service **Home Assistant Core Integration: Update entity** and as Target I choose my calendar to see if there is my newly created event. I still see the created event here. 

The created event is the one that starts at **13:30** and ends at **14:00**.
<img width="1220" alt="Screenshot 2023-10-05 at 16 57 04" src="https://github.com/RogerSelwyn/O365-HomeAssistant/assets/103631940/e902be6d-2e56-4151-9579-0c5f9e363ab2">

**Comment by RogerSelwyn** [comment]
This release should fix your problem - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.4.0

**Comment by krafcik02** [comment]
Hi Roger, you have solved the problem, thank you. 🙏
