### ISSUE TITLE
Missing Services

### ISSUE THREAD

**Issue by cstosgale** [RogerSelwyn/O365-HomeAssistant#172]
It looks like in the current version the services that are documented do not exist. The only one I can find is o365.scan_for_calendars?

I have also tried adding an event via the HA built in calendar: Create Event service, but that does not list o365 calendars.

**Comment by RogerSelwyn** [comment]
Please post your configuration with redacting the secrets.

**Comment by cstosgale** [comment]
Apologies, I've realised my mistake, I have enable_update: false in my configuration, which I'm guessing is why these services are not available.


o365:
  accounts:
    - account_name: csg-o365 # Do not use email address or spaces
      client_id: "xxxxxxx"
      client_secret: "xxxx"
      alt_auth_method: False
      enable_update: False
      email_sensor:
        - name: inbox
          max_items: 2
          is_unread: True
          download_attachments: False

**Comment by RogerSelwyn** [comment]
I would have expected the scan for calendars to be there, so I’ll check for that.

**Comment by cstosgale** [comment]
Ah yes the scan for calendars service was there.

I've now updated the enable_update property to True, but the services haven't appeared (despite a restart).

Will I need to remove the configuration and re-create it?

**Comment by RogerSelwyn** [comment]
No, they should be enabled after a restart. Again post your config ensuring you use the <> icon from the GitHub toolbar to surround your config in quotes so it displays properly. Earliest I will look at this is Sunday.

**Comment by RogerSelwyn** [comment]
Just looked at the code, you also have to have the right permissions, so you will need to re-authenticate. Do this by deleting the token as detailed here - https://rogerselwyn.github.io/O365-HomeAssistant/permissions.html#changing-features-and-permissions

**Comment by cstosgale** [comment]
Many thanks for your help, this sorted it!
