### ISSUE TITLE
Calendar Colors

### ISSUE THREAD

**Issue by jarodwsams** [RogerSelwyn/O365-HomeAssistant#173]
Not an issue, probably, but more of a question. Is it possible to pull the calendar colors that have been configured in O365 online? Currently, each calendar pulled is assigned a random color by HA. I'd like to have the color for each calendar pulled from the configuration that I've already curated in O365.

**Comment by RogerSelwyn** [comment]
I can add the color attribute to the calendar entity (there are two: `color`, which is one from a list; and `hexcolor`). I have no control over how it is displayed though. You'd probably need to put in a request to HA frontend team to read an attribute if available and use it in the display.

I'm afraid I haven't done any frontend stuff, so not really sure how to get that done.

**Comment by nathan-curtis** [comment]
Very useful.. If you add them it's easy enough to pull either to use.. Personally I'd uss hexcolor - most of the mushroom cards can use that unmodified on anything that takes a color variable

**Comment by RogerSelwyn** [comment]
I'll look at it in the next few days

**Comment by jarodwsams** [comment]
I've just installed the update. I'd be happy to put in a request to the HA front-end team. Where can I go to look at the data pulled by the o365 integration to give them an appropriate example/screenshot?

**Comment by jarodwsams** [comment]
I've started a Feature Request discussion in the Front-End GH. I don't expect HA would just use the data as it's imported by your code, but I've proposed the building of a "bridge" that would allow for custom integrations like this one to plug in the desired calendar color.

https://github.com/home-assistant/frontend/discussions/18465
