### ISSUE TITLE
Feature request: convert O365 Tasks sensor to 2023.11.x ToDo entity 

### ISSUE THREAD

**Issue by nathan-curtis** [RogerSelwyn/O365-HomeAssistant#174]
2023.11.x will introduce the ToDo entities

Yeah it just needs to happen. Google tasks and Todoist are being converted on launch

https://rc.home-assistant.io/blog/2023/10/25/release-202311/#there-is-a-lot-todo

**Comment by RogerSelwyn** [comment]
See this branch - https://github.com/RogerSelwyn/O365-HomeAssistant/tree/todo_entity

**Comment by RogerSelwyn** [comment]
Just to comment, the implementation of To-do as implemented by HA so far has a subset of functionality compared to that provided by O365. It has no concept of:

- Description
- Due date
- Reminder

If you want to create tasks with these attributes, you will need to use the services provided by the integration rather than the To-do Lists panel.

**Comment by nathan-curtis** [comment]
Totally Understand.  That's what we get with new features. I intend to put feature requests for ToDo to support for the missing parts if it's not already in progress.  I strongly suspect Todoist needs it too, and Google Tasks should as well. I haven't played with the beta to see what additions it's getting in the update. 

In any case the integration should support the built-in features else it's a discoverability issue at a minimum.

I would suggest of course not deprecating the old task sensors until there is feature parity on the builtin construct of course.

Maybe your code for the missing parts could even work the toto core to add the features...

**Comment by RogerSelwyn** [comment]
I have just moved all the data over to the ToDo as attributes as they were before, so people will see no change apart from the entity type change. I will of course identify it as a breaking change in the release notes at the right time. 

I don’t want to maintain two sets of sensors and two sets of services.

**Comment by SamBouwer** [comment]
I've just installed the todo_entity branch and it works great with Microsoft To Do lists! Sync is crazy fast (near instant). Thank you for developing this!

@nathan-curtis could you link your FR's in the Home Assistant Issues list here?

**Comment by nathan-curtis** [comment]
Will do.

Sent via the Samsung Galaxy S22+ 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by uSlackr** [comment]
How do I install a beta branch?


\\Greg
________________________________

**Comment by RogerSelwyn** [comment]
You need to download the repository and copy the relevant folder manually. Or I will probably create a beta release tomorrow. You will need 2023.11 for it to install.

**Comment by SamBouwer** [comment]
@uSlackr you can use `git clone -b todo_entity https://github.com/RogerSelwyn/O365-HomeAssistant.git` and then upload the contents of the downloaded \O365-HomeAssistant\custom_components\o365 folder into your home assistant \config\custom_components\o365 folder

**Comment by nathan-curtis** [comment]
> could you link your FR's in the Home Assistant Issues list here?

Which ones are you referring to specifically?  I dont have anything else but this.

**Comment by SamBouwer** [comment]
@nathan-curtis the one you are referring to here:
> I intend to put feature requests for ToDo to support for the missing parts

So you might not have created those yet ;)

**Comment by nathan-curtis** [comment]
Tracking now. Yeah may be a day or so have some things to get done first

**Comment by RogerSelwyn** [comment]
I'll probably tag a few posts, but I'm trying to get some views. I'm considering breaking up the monolithic O365 integration into smaller, more manageable items. If you have a view, please comment here:

[O365 --> MS365 - A potential big change - your views needed](https://github.com/RogerSelwyn/O365-HomeAssistant/discussions/234)
