### ISSUE TITLE
Feature Request: Integrate with Home Assistant ToDo

### ISSUE THREAD

**Issue by saya6k** [RogerSelwyn/O365-HomeAssistant#179]
Hi, since Home Assistant 2023.11.0, it supports todo as integration.

Now Todoist and Google Tasks supports it.

I wish this integration also supports Microsoft To-Do as integration.

**Comment by RogerSelwyn** [comment]
See this - https://github.com/RogerSelwyn/O365-HomeAssistant/issues/174
