### ISSUE TITLE
Setup issue v4.4.3

### ISSUE THREAD

**Issue by CarlBird** [RogerSelwyn/O365-HomeAssistant#180]
Receiving this error since updating to v4.4.3

------------
Logger: homeassistant.setup
Source: setup.py:288
First occurred: 13:00:25 (1 occurrences)
Last logged: 13:00:25

Error during setup of component o365
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/o365/__init__.py", line 64, in async_setup
    await _async_setup_account(hass, account, conf_type)
  File "/config/custom_components/o365/__init__.py", line 169, in _async_setup_account
    await do_setup(hass, account_conf, account, account_name, conf_type, perms)
  File "/config/custom_components/o365/setup.py", line 55, in do_setup
    keys = await coordinator.async_setup_entries()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/coordinator.py", line 92, in async_setup_entries
    query_keys = await self._async_query_sensors()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/coordinator.py", line 149, in _async_query_sensors
    CONF_QUERY: build_query_query(mail_folder, sensor_conf),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/classes/mailsensor.py", line 197, in build_query_query
    query = _add_to_query(query, "contains", "subject", subject_contains)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/o365/classes/mailsensor.py", line 214, in _add_to_query
    query.chain("and").on_attribute(attribute_name).contains(attribute_value)
    ^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'chain'

**Comment by RogerSelwyn** [comment]
Please can you post your config.

**Comment by RogerSelwyn** [comment]
Please can you check v4.4.4 fixes your issue - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.4.4

**Comment by RogerSelwyn** [comment]
Can you check in classes/mailsensor.py that it looks like this at the end. In particular the first `return query`. Also have you restarted after the upgrade?

```
def _add_to_query(query, qtype, attribute_name, attribute_value, check_value=True):
    if attribute_value is None or check_value is None:
        return query

    if qtype == "ge":
        query.chain("and").on_attribute(attribute_name).greater_equal(attribute_value)
    if qtype == "contains":
        query.chain("and").on_attribute(attribute_name).contains(attribute_value)
    if qtype == "equals":
        query.chain("and").on_attribute(attribute_name).equals(attribute_value)

    return query
```

**Comment by RogerSelwyn** [comment]
Please can you repost the error, so I can check it. Because I could replicate the error before and can't now after the fix.

**Comment by RogerSelwyn** [comment]
> The committed change has been applied and yes, restarted twice to be sure
> 
> ![image](https://user-images.githubusercontent.com/50060909/280335404-590b1fe4-8373-494d-8603-f9f34e4ac908.png)

This is the wrong version. Line 209 should read `return query`.

**Comment by RogerSelwyn** [comment]
Note my second message. If the screenshot of the code you posted is what you have, then you have v4.4.3 not v4.4.4.

Line 209 should read `return query`.
