### ISSUE TITLE
Group Calendars show as "Restored" / unavailable and don't show up in Calendar panel

### ISSUE THREAD

**Issue by sup3rm3ga** [RogerSelwyn/O365-HomeAssistant#182]
It seems Group calendar info is available elsewhere in the UI (various calendar cards, etc) but the entities are listed as "Restored" and they do not show up in the HA Calendar Panel. Is this a known issue? I'm having this problem on two separate installations.

**Comment by RogerSelwyn** [comment]
Please look at this issue - https://github.com/RogerSelwyn/O365-HomeAssistant/issues/181

If you can goto the latest beta. If not I'll look to fix it in a couple of weeks.

**Comment by sup3rm3ga** [comment]
Perfect, that worked! Thanks for the quick response.
