### ISSUE TITLE
Events missing - o365.new_todo

### ISSUE THREAD

**Issue by ChrizZz90** [RogerSelwyn/O365-HomeAssistant#187]
Don't know what happened but the only events which are available are:

- o365.scan_for_calendars
- 0365.scan_for_task_lists

But in the configuration.yaml I have updates for the account and for the todo_sensors enabled.

Based on fixtse's script my goal is to add new tasks in a dashboard and I used his [automation script](https://fixtse.com/blog/o365-card).

Do I have to add the o365.new_todo event manually?

Thanks

**Comment by RogerSelwyn** [comment]
Please post your config with secrets redacted.

**Comment by RogerSelwyn** [comment]
Also, are any errors shown in the system logs.

**Comment by ChrizZz90** [comment]
configuration.yaml

`o365:
  accounts:
    - account_name: HA # Do not use email address or spaces
      client_id: "***"
      client_secret: "***"
      alt_auth_method: False
      enable_update: True
      #email_sensor:
      #- name: inbox
      #  max_items: 2
      #  is_unread: True
      #  download_attachments: False
      #query_sensors:
      #  - name: "Example"
      #    folder: "Inbox/Test_Inbox" #Default is Inbox
      #    from: "mail@example.com"
      #    subject_contains: "Example subject"
      #    has_attachment: True
      #    max_items: 2
      #    is_unread: True
      #status_sensors: # Cannot be used for personal accounts
      #  - name: "User Teams Status"
      #chat_sensors: # Cannot be used for personal accounts
      #  - name: "User Chat"
      todo_sensors:
        enabled: True
        enable_update: True # set this to true if you want to be able to create new todos
`

**Comment by RogerSelwyn** [comment]
Please make die you are in the latest beta.

**Comment by ChrizZz90** [comment]
Just switched to v4.5.1b2 without any change

**Comment by RogerSelwyn** [comment]
I know I keep asking for things. Please can you post the full errors from your logs for `custom_components.o365` and `O365`. That errors looks like you are trying to call the service before it is installed. You can see the available services in `developer tools/services`

**Comment by ChrizZz90** [comment]
in developer tools / services I checked if the event is known, but it isn't.

In the HA core logs I have:

> 2023-12-23 21:46:41.201 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration o365 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
> 2023-12-23 21:47:18.476 WARNING (MainThread) [homeassistant.setup] Setup of o365 is taking over 10 seconds.
> 2023-12-23 21:48:51.650 ERROR (MainThread) [homeassistant.components.automation.todo_einkaufen_create_task] ToDo_einkaufen_create-task: Error executing script. Service not found for call_service at pos 1: Service o365.new_todo not found.

**Comment by RogerSelwyn** [comment]
Your automation will never work if the service (not event) has not been installed. I’ll take a look at the issue, maybe tomorrow, but probably Wednesday. 

Usually this type of thing is because the permissions are not setup right in the Azure app, so I’d expect to see an error in the log. 

I would make sure you have the permissions are correct on Azure, and then delete the token and re-authenticate.

**Comment by ChrizZz90** [comment]
I gave permissions to tasks.read and tasks.readWrite - anything else I have to grant for writing tasks?

**Comment by RogerSelwyn** [comment]
Have you deleted the token and reauthenticated?

**Comment by ChrizZz90** [comment]
not yet, just wanted to make sure the right permissions are granted

**Comment by RogerSelwyn** [comment]
Permissions should be ok for the todo/tasks.

**Comment by ChrizZz90** [comment]
alright, I deleted my secrets, created a new one, added it to the configuration.yaml and made a restart. But how can I reauthenticate? Do I need to remove the token file?

**Comment by RogerSelwyn** [comment]
Yes, I said delete your token. You didn’t need to change you Azure app if the permissions are right.

**Comment by ChrizZz90** [comment]
oh sorry, I misunderstood that. Reauthentication made it - now I have all of the events and it works :)

Thanks for your speedy help and Merry Christmas

**Comment by RogerSelwyn** [comment]
I'll try to add some warning in the logs as to what likely happened. I suspect you set up the integration with read only permissions, then added the update config settings and permissions afterwards. But the integration allows read only permissions to not restrict startup even when update is requested in the config (note that the token will still show read only, even if you update the azure app with update permissions), it just won't enable the services.

So deleting the token, allows it to refetch the requested and allowed update permissions, therefore enabling the services to be installed.

**Comment by RogerSelwyn** [comment]
Closed with v4.5.1b3
