### ISSUE TITLE
Renaming a to-do item, it's itemname stays as the old name ?

### ISSUE THREAD

**Issue by B-Hartley** [RogerSelwyn/O365-HomeAssistant#191]
Not sure if this is correct beahviour or not.
I create a todo item.

"ToDo Item1"

I do an update_item with rename: to change it change it's name to "ToDo Item2"
If I then try and do an update on the item "ToDo Item2" it doesn't exist.
The key to the todo item still seems to be "ToDo Item1"

Hope that makes sense ?

**Comment by RogerSelwyn** [comment]
I’ll check.

**Comment by RogerSelwyn** [comment]
I can't replicate this, when I configure as attached it works fine:

<img width="1256" alt="Screenshot 2024-01-03 at 14 38 20" src="https://github.com/RogerSelwyn/O365-HomeAssistant/assets/7115783/63d1b442-c5a8-407f-9ff0-d46398f61b62">

**Comment by RogerSelwyn** [comment]
I should have said, i renamed from something else to item 1, then renamed on to 2, then on to 3. No problem

**Comment by B-Hartley** [comment]
I agree, weird.
maybe it was fixed in your previous fix, maybe I was wrong.

Thanks anyway.
