### ISSUE TITLE
cannot set a due_datetime on a todo item

### ISSUE THREAD

**Issue by B-Hartley** [RogerSelwyn/O365-HomeAssistant#192]
When creating a ToDo item, the due_date: option seems to work fine, but due_datetime fails.

Is this intentional?

**Comment by RogerSelwyn** [comment]
Via the api, you can’t set a due date time (you can set a reminder date time). I think the example I have provided only has a date on it.

**Comment by B-Hartley** [comment]
ok, that makes sense. and I guess at the moment the home assistant todo item has no "reminder".
