### ISSUE TITLE
Home Assistant can't see the ToDo description

### ISSUE THREAD

**Issue by B-Hartley** [RogerSelwyn/O365-HomeAssistant#193]
Creating a ToDo item with a description works fine using todo.add_item
but if you view the todo item in home assistant, you can't see the description.

**Comment by RogerSelwyn** [comment]
Fixed in https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.5.3

**Comment by RogerSelwyn** [comment]
I'll probably tag a few posts, but I'm trying to get some views. I'm considering breaking up the monolithic O365 integration into smaller, more manageable items. If you have a view, please comment here:

[O365 --> MS365 - A potential big change - your views needed](https://github.com/RogerSelwyn/O365-HomeAssistant/discussions/234)
