### ISSUE TITLE
Support for editing tasks in the new To-do list editor

### ISSUE THREAD

**Issue by MasterDevwi** [RogerSelwyn/O365-HomeAssistant#194]
Thank you for adding support for viewing O365 tasks in the new To-do list UX in Home Assistant! While I can see all of my tasks, they seem to be read-only. I can't check any of them off, edit them, or add a new task. Is this on the roadmap?

**Comment by RogerSelwyn** [comment]
Assuming you have enabled update permissions for tasks (and if you have been able to rename one, it should be enabled), then you need to raise the query with the core. I don't control the new UI at all. You can also check if you can update using the services in the developer tools.

**Comment by B-Hartley** [comment]
It all works fine for me, so I suspect it's permissions on your O365 setup.

**Comment by MasterDevwi** [comment]
Ah, yes, that was it! Apparently I was missing enable_update for tasks (somehow I thought the one further up in YAML applied to everything). Thanks for the pointer! I'm glad I checked rather than waiting for editing support to be added. I would have waited forever. 😬
