### ISSUE TITLE
[Feature suggestion] Option to disable mail body as entity attributes

### ISSUE THREAD

**Issue by LazyTarget** [RogerSelwyn/O365-HomeAssistant#196]
Hi!

I am using this integration mostly to get counters on the number of Unread mails in my Inbox and Junk folders. For reminders and collecting insights

Unfortunately I have quite a lot of unread emails (I have set `max_items: 500`). There is no problem loading those mails.. but I then have noticed that the attribute values on those entities tend to clutter up the Developer Tools -> States page.

Perhaps we could introduce a `download_body: False` config on both the `email_sensor` and `query_senors` options?
Maybe even worth to make this a breaking change by defaulting to False and let people opt-in to that data if needed...

**Comment by RogerSelwyn** [comment]
I'll look into this.

**Comment by RogerSelwyn** [comment]
use `show_body: false' in v4.5.4

**Comment by RogerSelwyn** [comment]
I'll probably tag a few posts, but I'm trying to get some views. I'm considering breaking up the monolithic O365 integration into smaller, more manageable items. If you have a view, please comment here:

[O365 --> MS365 - A potential big change - your views needed](https://github.com/RogerSelwyn/O365-HomeAssistant/discussions/234)
