### ISSUE TITLE
Teams Shift

### ISSUE THREAD

**Issue by maurettoXD** [RogerSelwyn/O365-HomeAssistant#199]
It will be awesome if you can add "Shift" to you great addon! :D

**Comment by RogerSelwyn** [comment]
Sorry, this is not something I would plan to include. This started as a calendar has evolved significantly from there. It's not going to get into scheduling. Sorry.

**Comment by maurettoXD** [comment]
Thanks for answer, what i mean was just the possibility to see shifts scheduled and not creating one... :)

**Comment by RogerSelwyn** [comment]
Sorry, the answer is still no. It isn't supported in the library I use for interfacing to MG Graph API (https://github.com/O365/python-o365). You would need to get it added there first. Once it gets added there, raise a another issue here and I'll investigate.
