### ISSUE TITLE
Todo lists not updated

### ISSUE THREAD

**Issue by Earthweb-EWS** [RogerSelwyn/O365-HomeAssistant#201]
I've integrated a few Todo lists from my Personal Outlook account.
Today I have discovered that the lists are not updated.

When I start Home Assistant, the lists are updated, but after a while, changes are not visible and a old version of the list is available.
Restarting Home Assistant, the lists are updated, and after a while the problem is there again.
Calendar is is working, the problem is only in the Todo list integration.
No errors are showing at the Logging section, and also not on the console.

Home Assistant Version: 2024.1.3 (Docker)
O365-HomeAssistant: 4.6.1

If you needed more information, please notify me.

**Comment by RogerSelwyn** [comment]
Ok, I’ll take a look.

**Comment by RogerSelwyn** [comment]
Just had a look where I’m using it and it is updating. Can you check for errors in the logs. Also, how are you doing updates, via an external app or via HA?

**Comment by Earthweb-EWS** [comment]
The strange behavior is that it doesn't happen all of the time. Now it was working for 2 days and today it is broken.
I don't know in wich timeframe is is getting broken, so difficult to find an error or something what it caused.

**Comment by RogerSelwyn** [comment]
I would suggest you investigate whether you have a catching issue or not. If there is nothing in the logs, then it will be updating every few seconds (I think it is 30 seconds, but it might be shorter).

**Comment by Earthweb-EWS** [comment]
I haven't seen the problem again in the last few days. If it happens again I will reopen this issue, but it can be closed until then. Probably an external cause.
