### ISSUE TITLE
o365_new_todo not firing

### ISSUE THREAD

**Issue by vcdx71** [RogerSelwyn/O365-HomeAssistant#202]
HA 2024.1.5 running on OS 11.4

The service is registered and I can call it. Issue I'm seeing is that when a new todo is created the event doesn't fire. I'm trying to create an automation around new items being created. I've listened for events and it never fires.

Config:
o365:
  accounts:
    - account_name: mabrown
      client_id: "xxxxx"
      client_secret: "xxxx"
      alt_auth_method: False
      enable_update: True
      todo_sensors:
        enabled: True
        enable_update: True

Nothing in the logs. Thanks for any help.

**Comment by RogerSelwyn** [comment]
Fixed with - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.6.2
