### ISSUE TITLE
Add Event button missing

### ISSUE THREAD

**Issue by lloyda** [RogerSelwyn/O365-HomeAssistant#203]
Have added the integration, and have visibility of my O365 calendars.  However the add event button does not appear.

If I add a local calendar, the button appears, but I cannot select one of the O365 calendars for the event to be created in.  Remove the local calendar, the button disappears.

I have given the app  Calendars.ReadWrite permission.

Any thoughts?

**Comment by RogerSelwyn** [comment]
Have you enabled updates in config.yaml?

**Comment by RogerSelwyn** [comment]
https://rogerselwyn.github.io/O365-HomeAssistant/installation_and_configuration.html#configuration-variables

**Comment by lloyda** [comment]
I thought you had it with the enable updates option. But that has made no difference. However that give me some entries in the log, and it looks like I need mail.send as well.

Anyway, I now have the button.  Thanks for the very speedy response.
