### ISSUE TITLE
Question/Feature Request: Ability to configure tracking of new "To-Do Lists"

### ISSUE THREAD

**Issue by JS876** [RogerSelwyn/O365-HomeAssistant#205]
Hi, 

I searched through the documentation and GitHub issues, but didn't find anything.

Is there a way to prevent the tracking of new To-Do Lists, similar to the "track_new_calendar" configuration variable? If not, would that be a possible future enhancement? 

Thanks!

**Comment by RogerSelwyn** [comment]
I'll look to add the capability over the next couple of weeks.

**Comment by RogerSelwyn** [comment]
Updated docs - https://rogerselwyn.github.io/O365-HomeAssistant/installation_and_configuration.html#todo_sensors
