### ISSUE TITLE
Feature request: Able to get and filter by Flagged state

### ISSUE THREAD

**Issue by LazyTarget** [RogerSelwyn/O365-HomeAssistant#206]
Hi,

Would it be possible to query emails by their "flagged"-state. Is that some thing that is exposed by the API?

I want to be able to list and count the number of flagged emails
Would also be nice with the same for "Pinned" emails :)

**Comment by RogerSelwyn** [comment]
Flag status will be in the next release. Pinned is not available in the api as far as I can see.

**Comment by RogerSelwyn** [comment]
Beta just released - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.7.0b1
