### ISSUE TITLE
personal accounts need to change the manifest

### ISSUE THREAD

**Issue by galoi9** [RogerSelwyn/O365-HomeAssistant#209]
Took me a bit to find this, but you may want to update the documenation:
https://learn.microsoft.com/en-us/answers/questions/1166348/cant-set-supported-account-types-to-personal-micro

**Comment by RogerSelwyn** [comment]
Sorry, but I don't understand the problem. Perhaps you can raise a PR against the documentation with your suggested changes.

Thanks
