### ISSUE TITLE
Calendar Filter - Not removing events based on list of exclusion

### ISSUE THREAD

**Issue by dallombra** [RogerSelwyn/O365-HomeAssistant#211]
Hello, I've tried many different formatting for the 'calendar - exclude' feature, in order to remove events that contains this string: _(via Café)_

No matter what I tried and I also searched a lot online, I can't figure out the correct way to write the exclusion code in the yaml configuration.

**Comment by RogerSelwyn** [comment]
```
    exclude:
     - "(via Café)"
```

**Comment by dallombra** [comment]
thanks for the suggestion, but that didn't work either...does the filter need some wildcard (i.e. */%) in order to work?

The actual calendar event would have a longer name, with the portion in bracket being just the last part: so the event would be "XXXX XXXX (via Café)"

**Comment by RogerSelwyn** [comment]
I'm afraid it works fine in my environment. Do you have any errors in your logs?

<img width="529" alt="Screenshot 2024-03-04 at 09 54 08" src="https://github.com/RogerSelwyn/O365-HomeAssistant/assets/7115783/e6c1642a-ba16-4e6b-a14a-134e4d23bb31">

<img width="571" alt="Screenshot 2024-03-04 at 09 56 51" src="https://github.com/RogerSelwyn/O365-HomeAssistant/assets/7115783/38482c6a-b84c-4d00-aaaa-2261e46fc32e">

<img width="1381" alt="Screenshot 2024-03-04 at 09 55 18" src="https://github.com/RogerSelwyn/O365-HomeAssistant/assets/7115783/aeb43f4a-c6a3-4030-8a92-95315e84f7d3">

**Comment by dallombra** [comment]
Could it be related to the fact that the events I'm trying to filter are All-day events and not regularly timed events?

**Comment by RogerSelwyn** [comment]
Int shouldn't do, but I'll take a look when I get a chance.

**Comment by RogerSelwyn** [comment]
Had a moment. No, that still works fine. Any errors in your logs?

**Comment by dallombra** [comment]
No errors in the logs.

I've tried like the below as well, in case the "é" was the issue, still all events are showing up.

```
 entities:
  - device_id: Calendar
    end_offset: 24
    name: Calendar
    track: true
    exclude:
     - "(via Caf"
```

**Comment by RogerSelwyn** [comment]
Sorry, I can't see why to doesn't work for you. I'd have to provide a debug version. Probably tomorrow...

**Comment by dallombra** [comment]
Found the issue! Sorry I have many calendars in the Yaml and I didn't notice that the one I was trying to filter was somehow duplicated in the config file.

I had applied the filtering only on the first instance, without realising there was a second copy below that was effectively overwriting the filter!

All sorted. Thanks for the help.

**Comment by dallombra** [comment]
Indeed that's what I did and it works perfectly now!
