### ISSUE TITLE
Feature request: Assigned to value of a ToDo Task

### ISSUE THREAD

**Issue by Sycend** [RogerSelwyn/O365-HomeAssistant#212]
Thanks alot for your passion into this project ❤️
would it be possible to view or set the assigned to state of a ToDo Task?
Greatings from Frankfurt :)

**Comment by RogerSelwyn** [comment]
This will be in the next release of the integration. No target date as yet. You can always look at the commit and add to your install if you want it sooner.

**Comment by RogerSelwyn** [comment]
Closed with latest release

**Comment by Sycend** [comment]
Thanks alot :D
Maybe I overlooked it, I saw changes that a state, like started/not started was added. Which is also awesome :D
What I meant was the assigned state, speaking of which person a task i assigned to.

**Comment by RogerSelwyn** [comment]
Always worth being explicit 😉. I'll take a look over the next few days if that is available and meaningful.

**Comment by RogerSelwyn** [comment]
Unfortunately the 'Assigned To' information is not available in the MS api as yet. I know the link below is old, but if you follow through to the MS documentation you can see it is still true.

https://learn.microsoft.com/en-us/answers/questions/756180/assigned-task-to-do-not-find

**Comment by RogerSelwyn** [comment]
I'll probably tag a few posts, but I'm trying to get some views. I'm considering breaking up the monolithic O365 integration into smaller, more manageable items. If you have a view, please comment here:

[O365 --> MS365 - A potential big change - your views needed](https://github.com/RogerSelwyn/O365-HomeAssistant/discussions/234)
