### ISSUE TITLE
Doku for monitoring other users teams status

### ISSUE THREAD

**Issue by matzingerhh** [RogerSelwyn/O365-HomeAssistant#213]
Dear Roger,
By reading the lates release notes I found the enhancement „monitor other users teams status“.

Am I right that I can use this for checking eg my business teams status where I do not have access to graph. This would unlock some little automation ideas for Ha.

I checked the doku but there I was not able to see how it is working. 
I would appreciate if you can confirm my understanding and show a little sample how to do it?
many thanks and kind regards from Hamburg

Mathias

**Comment by RogerSelwyn** [comment]
It means you need to have permissions within ms teams to access another users status using the permissions specified in the documentation. So you still need to be able to create an app within Azure and add permissions as specified. It would then use the credentials you set up within the Azure app, and the login when you authenticate.

**Comment by matzingerhh** [comment]
Hi Roger,
Yes I have an app for my *@outlook.com account. Works fine and I really like it.

 But for my business account I do not have auth to set up an app.
I think sec rules by our it department.

My idea was to use my private outlook.com account to monitor the business accounts status. 

so I would add my business account in the contacts of the private account. There I can get the status. But how would I get it Via o365 integration. 
Kind regards 
Mathias

**Comment by RogerSelwyn** [comment]
Sorry no.  The account that logs in must have access to all the services you are trying to access. Your outlook account won’t have access to your business teams account.

**Comment by RogerSelwyn** [comment]
Just to add, personal accounts don’t have MS Teams access via the api.

**Comment by matzingerhh** [comment]
Thanks for clarification. 
kind regards 
Mathias
