### ISSUE TITLE
Error in config after update

### ISSUE THREAD

**Issue by jorgemarmor** [RogerSelwyn/O365-HomeAssistant#214]
After an update, it seems that my previously working config is not working. I haven't been able to find how to solve it. 

I would appreciate any help.

This is what I get when checking the config file:

Component error: o365 - cannot import name 'ServiceValidationError' from 'homeassistant.exceptions' (/usr/src/homeassistant/homeassistant/exceptions.py)

**Comment by RogerSelwyn** [comment]
Please post the whole error, also what version of O365 you are using and what the previous version. Also what version of home Assistant you are using.

**Comment by RogerSelwyn** [comment]
It seems likely you are on a version of HA that is at least 4 months old since ServiceValidationError was added to HA about then. Your options are to upgrade HA to a newer version, or downgrade O365 integration to your last working version.
