### ISSUE TITLE
Delay when completing a to-do task on Home Assistant

### ISSUE THREAD

**Issue by h3nrytan** [RogerSelwyn/O365-HomeAssistant#217]
Hello.

Thank you for maintaining this integration. 

I notice whenever I complete one of to-do task on Home Assistant, immediate sync to Microsoft To Do but there is a delay (about 20 seconds or more) for it to move to completed section on Home Assistant. 

Delay does not happen when I create a new task via Home Assistant.

Currently on HA 2024.3.3 with your latest release 4.7.0

**Comment by RogerSelwyn** [comment]
Unfortunately I have no control over the core ToDo panel and how it updates. I can tell you that immediately after the update is performed I trigger an update of data on the entity, which normally happens immediately. For me when I tick a ToDo on the HA ToDo panel, it gets moved to the completed section within a second.

**Comment by h3nrytan** [comment]
Hello @RogerSelwyn 

Thank you for your quick feedback. That's great to know. 

Is there a setting that I'm required to follow? 

I've tried reconfiguring by having new ID and Secret Key, rebooted HA, for a brief moment it was fast but not sure what happened along the way it got slow again.

**Comment by h3nrytan** [comment]
Hello @RogerSelwyn 

I think I've solved it. Recreated a new list and it's fast now.

Will use the new list.

Thanks anyway!
