### ISSUE TITLE
Documentation Bug: Status Sensor:  email_address keyname invalid (should be email)

### ISSUE THREAD

**Issue by nathan-curtis** [RogerSelwyn/O365-HomeAssistant#218]
Doc link:
https://rogerselwyn.github.io/O365-HomeAssistant/installation_and_configuration.html#status_sensors-not-for-personal-accounts

For Status Sensors (Adding additional users)

Lists:

Key | Type | Required | Description
-- | -- | -- | --
email_address | string | False | Enter email address to monitor status for. enable_update key must not be present.

This throws an error in Home Assistant - keyname not valid for status sensor.

According to schema.py:
```
STATUS_SENSOR = vol.Schema(
    vol.All(
        {
            vol.Required(CONF_NAME): cv.string,
            vol.Optional(CONF_ENABLE_UPDATE, None): bool,
            vol.Optional(CONF_EMAIL, None): cv.string,
        },
        cv.has_at_most_one_key(CONF_ENABLE_UPDATE, CONF_EMAIL),
    )
)
```

Therefore: the keyname should be email - not email_address

Docs Instead should be:

Key | Type | Required | Description
-- | -- | -- | --
email | string | False | Enter email address to monitor status for. enable_update key must not be present.

using keyname email - not email_address, in fact provides desired result.

**Comment by RogerSelwyn** [comment]
Thanks, documentation corrected.
