### ISSUE TITLE
O365 homeassisant

### ISSUE THREAD

**Issue by Niko3003** [RogerSelwyn/O365-HomeAssistant#221]
After the latest update the integration is not working anymore
I got ha version 2024.4.3 and ha os 12.0
Running virtual on a Synology Nas.
I updated yesterdaymorning to  the latest version and after this the integration could not make a connection.
I use the calendar info and send some e mail notification
 Both don't work
In the log I see inbox not found from query_sensors config entry - inbox /test_inbox - entity not created.
Al of my entity's  are red and saying the entity is not available.
A can not see a backup is there a way to downgrade to an earlier version 

Niko

**Comment by Niko3003** [comment]
Hi I'm using 4.71 coming from I suppose 4.70
Only using thecalendar and the mail (notification only, so only sending mail)
Her you have the part of configuration.yaml about o365
o365:
  accounts:
    - account_name: mattheus #Do not use email address or spaces
      client_id: "92ded409-9437-418b-96d1"
      client_secret: "uA_8Q~WKXD~nAHyJ2In5kLRWiyxLWw64zqz"
      alt_auth_method: False
      enable_update: True
      track_new_calendar: True
      email_sensor:
        - name: inbox
          max_items: 2
          is_unread: True
          download_attachments: False
      query_sensors:
        - name: "Example"
          folder: "Inbox/Test_Inbox" #Default is Inbox
          from: "niko@smurfies.nl"
          subject_contains: "Example subject"
          has_attachment: True
          max_items: 2
          is_unread: True
#      status_sensors: # Cannot be used for personal accounts
#        - name: "User Teams Status"
#      chat_sensors: # Cannot be used for personal accounts
#        - name: "User Chat"
#      todo_sensors:
#        enabled: False
#        enable_update: False # set this to true if you want to be able to create new
  
The only error I found was in the earlier post

Yes i'me having a daily backup

Downgrade town earlier version does not work
![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/96992289/88c285a8-2faa-4a98-a387-aac1f3603bf6)

**Comment by RogerSelwyn** [comment]
That isn't HACS you are using for the downgrade, I posted a link that provided details on how to use it. That looks like you are trying to update HA.

As I asked for before, please post an exact copy of the error on your logs. You have summarised it before, which does not provide what I need.

**Comment by Niko3003** [comment]
Folder - Inbox - not found from query_sensors config entry - Inbox/Test_Inbox - entity not created 
 12:36:55 – (FOUT) Office 365 (aangepaste integratie)
Is the only thing I found in the logs, I've just restarted ha
For some reason it doesn't connect to ms365 anymore
![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/96992289/8a15ba07-ea23-47fe-82d3-137da3cc5071)
When I'm trying to downgrade through... I see this  no way I could select anotherversion then 4.7.1
That is the reason I tried the solution mentioned in thescreen.

Niko

**Comment by RogerSelwyn** [comment]
I assume the error looks like this:
`2024-04-16 10:55:26.056 ERROR (MainThread) [custom_components.o365.coordinator] Folder - Test_Inbox - not found from query_sensors config entry - Inbox/Test_Inbox - entity not created`

I would remove the query sensor, since you don't have the relevant folder `Inbox/Test_Inbox` available. This should not stop the calendar being created.

With regards downgrades, you would need to take this up with HACS. You can try toggling the beta button to see if that will repopulate the dropdown properly.

You have said it doesn't connect to MS365 anymore. It what way do you identify it is not connecting to MS? Is it just the entities show as unavailable? You can try adding debug logging, which will give you some more events in your log to show what updates are being performed.

``` yaml
logger:
  default: warning
  logs:
    custom_components.o365: debug
```

**Comment by Niko3003** [comment]
I don't see any error even with debug on
But excluding the query did the trick it's now working fine again
I can see the the calendars again
Thanks for support

Niko
