### ISSUE TITLE
ToDo reminders only adding as 11am

### ISSUE THREAD

**Issue by Tussca** [RogerSelwyn/O365-HomeAssistant#225]
Any ToDo reminder I create, if I add reminder date/time it is created as 11am. Would there be some config during install I messed up or would this possibly be an error with the integration?

**Comment by RogerSelwyn** [comment]
I could not directly replicate this issue, but did notice a slightly different issue around reminder time which I have fixed in v4.7.3. Please can you check and see if your problem is resolved.

**Comment by Tussca** [comment]
Nope, it gets the day fine just not the time - like if I set the reminder to be tomorrow it create the task with a reminder for tomorrow at 11am.

![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/128939996/c3b2ef44-e292-4116-bde3-a615852553b5)


any idea where that would be broken on my side then?

**Comment by RogerSelwyn** [comment]
All I can say is that I can't replicate the issue. 

- Where are you based, I guess in the US since you have m/d/y format? 
- Where are you checking the reminder time? When I look on my iPhone and in MS To Do app on my Mac it shows correctly, also in Developer Tools/states?
- Are you using the latest version of the integration?

**Comment by RogerSelwyn** [comment]
Bear in mind also that any time you put in there is in UTC since HA does not include a time zone for service call provide date times.

**Comment by Tussca** [comment]
I'm in Canada, how do you change the date format to d/m/y?


Okay does seem like a timezone issue. Thank you for your help!

Is there a way to change it? The HA timezone or tell the integration to convert before actually making the task? Or do I just have to convert the time myself?

**Comment by RogerSelwyn** [comment]
You can use yaml model and put in the date in the format 2024-05-08T18:00:00-0700. This is the same as 1am UTC on the 9th.

**Comment by RogerSelwyn** [comment]
> Is there a way to change it? The HA timezone or tell the integration to convert before actually making the task? Or do I just have to convert the time myself?

This type of question is often asked, but since HA core doesn't pass through a timezone from the frontend, then the integration which runs on the backend server side has no idea where you are in the world, so handles everything as far as possible in UTC.

**Comment by Tussca** [comment]
Okay thanks for your help!
