### ISSUE TITLE
Feature Request: Support for checklist items with To-Do tasks

### ISSUE THREAD

**Issue by SquidBytes** [RogerSelwyn/O365-HomeAssistant#226]
Just started using this as I'm trying to use a To-Do list.
Microsoft To-Do Web & Application supports "Steps" underneath various tasks
![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/145411069/b6b80ded-ed1d-474b-b8e9-9256e60e32ec)

Taking a peek at the API documentations it appears these are able to be obtained.
API Docs: https://learn.microsoft.com/en-us/graph/api/resources/todo-overview?view=graph-rest-beta&preserve-view=true#checklist-item

I figured I would open a feature request instead of going down the rabbit hole trying to implement it myself.

I do not think these Steps/Checklists would be able to use the Home Assistant To-Do card. But they should be able to be used in Markdown cards.

**Comment by RogerSelwyn** [comment]
The capability to retrieve checklists would need to be added to the library this integration uses to access MS365., it isn’t currently supported. 

https://github.com/O365/python-o365

**Comment by SquidBytes** [comment]
Ahhh. That's why, when peeking at the code, I didn't see any API functions.
That makes sense. I'll close this and if it ever does to implemented into `python-o365` I can either re-open or you may already be on it.
Thank you
