### ISSUE TITLE
New Calendar Events not get added to HA Calendar (QUESTION)

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [RogerSelwyn/O365-HomeAssistant#229]
If I add a new event to my Outlook Agenda it not gets added in my Calendar UI in Home Assistant. I only have the basic configuration now in my configuration.yaml (name and secrets). Do I have to add "enable_update: true" also to my configuration.yaml so newly added Agenda events also get automatically added to my Calendar UI in Home Assistant?

**Comment by RogerSelwyn** [comment]
By `Outlook Agenda` do you mean calendar? Do you have any calendar events appearing in HA, or is it just new ones that aren't there?>

**Comment by smarthomefamilyverrips** [comment]
> By `Outlook Agenda` do you mean calendar? Do you have any calendar events appearing in HA, or is it just new ones that aren't there?
> 
> Do you don't need to set enable_update to true, that is for updating events from within HA.

I mean the calendar within the outlook.com email address that I used to setup the Azure App that I linked to O365 integration. I see all events that where already presents in my Calendar during the time of setup of the integration, only newly added events not show up.wothin HA.

**Comment by RogerSelwyn** [comment]
I think the update interval is 60 seconds. 

- Do they appear if you restart HA? 
- Can you see them in Developer Tools? 
- Any errors in the logs?

If using the HA Calendar pane, I don't know if it refreshes without you leaving it and going back again.

**Comment by smarthomefamilyverrips** [comment]
@RogerSelwyn after watching F1 Qualifying first and now checking again the event now is available also in the HA Calendar 👍🏻 so maybe was a small glitch or me being inpatient. I will close the issue. Thank you for your help and the effort you put in the O365 integration! 💯
