### ISSUE TITLE
Using Attribute State in template sensor (QUESTION)

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [RogerSelwyn/O365-HomeAssistant#230]
@RogerSelwyn I want to us a attribute state in a template sensor but now i have the below in attributes

data: 
- summary: Busy
  start: '2024-05-19T20:00:00+00:00'
  end: '2024-05-19T20:15:00+00:00'
  all_day: false
  description: ''
  location: ''
  categories: []
  sensitivity: Normal
  show_as: Busy
  attendees: []

I would like to use the summary state but somehow it seems this is not seen as a attribute, only data i am able to get state off .... you have any idea if i can use the state of summary somehow for a template sensor?

**Comment by RogerSelwyn** [comment]
Also here https://github.com/RogerSelwyn/O365-HomeAssistant/issues/13#issuecomment-1009095758

**Comment by smarthomefamilyverrips** [comment]
@RogerSelwyn 

this template did do the trick for me to acces the value I needed

{{ state_attr('calendar.cam4_agenda_cam4', 'data')[0].summary }}

Thank you for your help 💯

**Comment by smarthomefamilyverrips** [comment]
Close as solved! 👍
