### ISSUE TITLE
Semantic versioning with breaking changes

### ISSUE THREAD

**Issue by bjornwiberg** [RogerSelwyn/O365-HomeAssistant#233]
I want to start by thanking you for an amazing job with this great HACS integration.

Now to the point.
Since you follow semantic versioning and added a breaking change now in v4.8.0 I advice you to follow the convention of semantic versioning and make a major release instead with v5.0.0

Here's some guidelines for semantic versioning
- Major version is only needed when breaking changes are introduced (can include everything from a minor update also)
- Minor version for features and can NOT contain any breaking changes (can include everything from a patch update also)
- Patch version for dep. updates, chores, reactors, docs, and bug fixes and can NOT contain any new features or breaking changes.

This helps your users to keep track if they want to still keep the current version or choose to update when there are a breaking changes in a major version bump.

With this way you can still maintain your package with bug fixes in version 4 but also improve it with new features in version 5.

I hope this can help you.

**Comment by RogerSelwyn** [comment]
Thank you, good advice.

**Comment by RogerSelwyn** [comment]
I'll probably tag a few posts, but I'm trying to get some views. I'm considering breaking up the monolithic O365 integration into smaller, more manageable items. If you have a view, please comment here:

[O365 --> MS365 - A potential big change - your views needed](https://github.com/RogerSelwyn/O365-HomeAssistant/discussions/234)
