### ISSUE TITLE
Calendar/Agenda events suddenly show hour early in HA Calendar.

### ISSUE THREAD

**Issue by smarthomefamilyverrips** [RogerSelwyn/O365-HomeAssistant#237]
While working correct so far on version 4.8 I suddenly today noticed that all events synced with my Outlook calendar show a hour early, in my Outlook Agenda the events start at 17:00 local time what is the correct time but since today or maybe yesterday it started showing up as 16:00 in the HA calendar while this was not the case before. I not did change anything, only thing that happened is HA did sut down last night as cause of power failure, but am not sure this is the cause as the HA clock still shows the correct local time.

**Comment by RogerSelwyn** [comment]
Assuming you are in the uk, the dates that shows in the data attribute you can see in the Developer menu are in UTC. An event that starts at 10am BST will be down as 9am UTC.  Assuming those are showing correctly then you would need to raise the issue with the core team. 

There is no reason a reboot would change anything in itself. As always with these things I would ask what has been changed on the server.

**Comment by smarthomefamilyverrips** [comment]
> Assuming you are in the uk, the dates that shows in the data attribute you can see in the Developer menu are in UTC. An event that starts at 10am BST will be down as 9am UTC. Assuming those are showing correctly then you would need to raise the issue with the core team.
> 
> There is no reason a reboot would change anything in itself. As always with these things I would ask what has been changed on the server.

I am actually in Romania, the strange things is it all was fine before, every day at 17:00 I have a meeting for work and 15 minutes in front I get a announcement through HA, today I suddenly got it at 15:45 and noticed all appointments now show at 16:00. I will invest a bit more tomorrow and will report back what I could find. Thanks for your response!

**Comment by smarthomefamilyverrips** [comment]
@RogerSelwyn I did have a look and actually it is totally not related to the integration. Unfortunately I also not know how to solve it, after few hours searching the cause and solution I gave up. 

I did make.a seperate outlook account specifically for this integration and did subscribe to my work agenda using a ics link. While this was working perfect so far now for whatever reason the scheduled appointments show 1 hour early in the linked outlook agenda I use for this integration while in my original work agenda the appointments still show on correct time. I not made any changes on either accounts. I searched Google for any cause or solution, checked all time zone settings if are on correct time zone and all is as should be (and as was before) ... so for me is a mystery why the appointments suddenly show up a hour early on the subscribed agenda compared to original work agenda. I doubt you will have any suggestion for this but still wanted to share what was happening just in case you would have any suggestions that could solve this weird issue I have.

If you have also no idea or any tips please feel free to close this issue. Thank you!
