### ISSUE TITLE
Todo due dates - Showing wrong due date in todo list

### ISSUE THREAD

**Issue by twofacedsquare** [RogerSelwyn/O365-HomeAssistant#239]
There seems to be a timezone or offset issue when using the todo integration. 

The task in Microsoft Todo is set to a specific date:

![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/26843110/6bb1b195-c74e-44d8-90d2-e023fc943ae6)

Which seems to be pulled into the entity attributes correctly
![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/26843110/cbd99558-9c22-47e0-9c02-a24ed106ef16)

But when it is viewed from the todo lists it shows 1 day behind

![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/26843110/3930a6b0-eecc-4e93-91a7-ebe9b06a4750)

![image](https://github.com/RogerSelwyn/O365-HomeAssistant/assets/26843110/a56b8c0c-6ada-45fa-bd34-429b0537b8f7)

I don't have this issue when creating a task in the stock todo lists and setting a due date, and I have validated that my timezone is set correctly. 

I also have other integrations pulling things with dates (Waste collection) that works correctly

Let me know what logs you need

**Comment by RogerSelwyn** [comment]
I’m away on holiday so won’t look at this for a couple of weeks. I’d have to look at the logic of what the core is doing as to whether it is a core issue or an integration issue. In think due date is only a date, so it maybe thinking it is a utc date time at midnight(which is what the integration works in) and converting to local date where I assume you are in the US.

**Comment by twofacedsquare** [comment]
Thanks!

Yes I am in Mountain Time, and agree it does seem to be a timezone/UTC conversion.

I have the O365 calendar integrated as well and dates set there work correctly, so it does seem to be isolated to todo

**Comment by RogerSelwyn** [comment]
Should be fixed with v4.8.2

**Comment by RogerSelwyn** [comment]
I would suggest moving over to https://github.com/RogerSelwyn/MS365-ToDo since this will be the go forward app for To Dos.

**Comment by twofacedsquare** [comment]
Thanks! Works!

Will get migrated soon
