### ISSUE TITLE
2024.7 - Setup of "o365" taking longer than 300 seconds 

### ISSUE THREAD

**Issue by bigbeefyangus** [RogerSelwyn/O365-HomeAssistant#240]
Hello! Just updated my instance to stable 2024.7.0 and the startup for the integration is taking a long time to start up and the "Teams Presence" sensor is unavailable. Was working fine in 2024.6.4.

Only errors and warnings I can see in the logs are as follows:

```
**ERROR**
Logger: homeassistant.setup
Source: setup.py:406
First occurred: 12:02:01 PM (1 occurrences)
Last logged: 12:02:01 PM

Setup of 'o365' is taking longer than 300 seconds. Startup will proceed without waiting any longer
```

```
**WARNING**
Logger: homeassistant.bootstrap
Source: bootstrap.py:733
First occurred: 11:57:51 AM (5 occurrences)
Last logged: 12:01:51 PM

Waiting on integrations to complete setup: {('o365', None): 1120885.252891238}
```

```
**WARNING**
Logger: homeassistant.setup
Source: runner.py:190
First occurred: 11:57:11 AM (1 occurrences)
Last logged: 11:57:11 AM

Setup of o365 is taking over 10 seconds.
```

**Comment by RogerSelwyn** [comment]
What version of home Assistant are you running?

**Comment by bigbeefyangus** [comment]
HA Version 2024.7.0 - though I just noticed after several restarts throughout the afternoon it seems to be working now and the errors are gone. I had restarted 3-4 times before posting an issue so who knows. I'll reopen if the issue comes back.

**Comment by RogerSelwyn** [comment]
It is untested on 2024.7.x since I’m away on holiday. Oops I should have asked what version on the integration you are using.
