### ISSUE TITLE
MS client ID / key change as of June 24

### ISSUE THREAD

**Issue by Hasenhirn** [RogerSelwyn/O365-HomeAssistant#241]
Hi and thank you for all the work you put in this! As of June 24, MS made the change that all apps must be registered in a directory.

https://learn.microsoft.com/en-us/entra/identity-platform/reference-breaking-changes#applications-must-be-registered-in-a-directory

It does not apply to already added apps, just new ones. Could you maybe provide a different approach to connect to e.g. todo or is that impossible?

Cheers

**Comment by RogerSelwyn** [comment]
The guidance says that you can create your own directory. Does that not work for you?

**Comment by Hasenhirn** [comment]
You do need an Dev or Azure Account, I just signed up for the Azure Free Tier and will test it.

**Comment by Hasenhirn** [comment]
Update: You can sign up to an Azure Free Account and use the Microsoft Entra ID to create an Application and a Secret Key. As soon as you sign up, your directory is created as "Default Directory" https://portal.azure.com


New Issue:
When trying to register the app trough home assistant, my local IP is used for the redirect uri. This is a problem, because in the application configuration within Microsoft Entra ID, you are only allowed to use https (third image).

Question:
Is there any way to let O365 rewrite the redirect uri to a custom string? Problem is in second image.

![O365 HA 1](https://github.com/user-attachments/assets/c6d0716e-82eb-4f49-99e5-801fc44362c3)

![O365 HA 2](https://github.com/user-attachments/assets/46cd1c30-d642-444d-b176-4a861aeb9687)

![O365 HA 3](https://github.com/user-attachments/assets/88bb21ef-6911-47bf-8d92-21ec2988e4a2)

**Comment by RogerSelwyn** [comment]
Use the default authentication method rather than the alternate, or access your ha when authentication via the external URL.

**Comment by Hasenhirn** [comment]
Thank you for your awesome and patient help so far. Now the following error occurs, encoded within the return uri.

> The request is not valid for the application's 'userAudience' configuration. In order to use /common/ endpoint, the application must not be configured with 'Consumer' as the user audience. The userAudience should be configured with 'All' to use /common/ endpoint

It seems to be a MS issue, but maybe you have an idea? I looked through all of the Entra ID Configs and even the Manifest Editor but could not find and userAudience parameter ...

**Comment by RogerSelwyn** [comment]
Sorry no idea. I would just go through and recreate the application following the instructions carefully. That usually works

**Comment by RogerSelwyn** [comment]
Did you take note of this:

```
2. Create a new App Registration. Give it a name. In Supported account types, choose one of the following as needed by your setup:
   * `Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)`.   
   * `Accounts in any organizational directory (Any Azure AD directory - Multitenant)` 

   **Do not use the following:** 
   * `Accounts in this organizational directory only (xxxxx only - Single tenant)` 
   * `Personal Microsoft accounts only`
```

**Comment by Hasenhirn** [comment]
I am such an idiot. Yes I totally read over the configuration guide that you have. Problem solved ... thanks again for your patience!

**Comment by RogerSelwyn** [comment]
Thank you 🙏
