### ISSUE TITLE
can't even get past the first prerequisite

### ISSUE THREAD

**Issue by onlytobeking** [RogerSelwyn/O365-HomeAssistant#246]
Am I being an idiot or aren't you allowed to make a new app registration with a new account in the azure portal?

**Comment by RogerSelwyn** [comment]
https://learn.microsoft.com/en-us/entra/identity-platform/reference-breaking-changes#applications-must-be-registered-in-a-directory

**Comment by onlytobeking** [comment]
Yeah, tried to sign up for developer program. And just get a message saying something like, thank you for applying but you currently doesnt qualify for microsoft developer program. Found some people on reddit having similar problems. For some people it was just waiting a while to get accepted, some people still waiting.. six months later..

**Comment by RogerSelwyn** [comment]
Sorry, but I’m afraid there is nothing I can do to help. To use the Azure api, you need an app, and unfortunately MS have restricted how they can be created.
