### ISSUE TITLE
Multiple account support

### ISSUE THREAD

**Issue by aaronpowell** [RogerSelwyn/O365-HomeAssistant#25]
I've got multiple M365 accounts, is it possible to provide multiple tokens for the different tenants so I can have all the accounts listed?

**Comment by RogerSelwyn** [comment]
It isn't currently. I'll have a think on it and see how easily it can be done.

**Comment by RogerSelwyn** [comment]
Alpha version of code to support multiple accounts is here - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v3.0.0a1

I have tested with two email accounts within one tenancy (one client id/secret), but I believe it should work with multiple. token is then named to include the account name (which is required) in the filename, as is the calendars yaml.

**Comment by RogerSelwyn** [comment]
Just to add, this is a very major change to the code, so use with care.

**Comment by loryanstrant** [comment]
I'm curious as to how the Presence will work for this one?
I'm guessing you'd have a separate entity for the presence from each tenant?

**Comment by RogerSelwyn** [comment]
> I'm curious as to how the Presence will work for this one?
> I'm guessing you'd have a separate entity for the presence from each tenant?

Yes, there will be a separate entity for each presence sensor. Each 'account' will use a separate login token to O365.

**Comment by RogerSelwyn** [comment]
I intend to move this to beta status in the coming days unless anyone comes back with comments. This will allow wider testing before full release.

https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v3.0.0a9

**Comment by RogerSelwyn** [comment]
Beta release here - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v3.0.0b0

**Comment by RogerSelwyn** [comment]
Feature included with - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v3.0.0
