### ISSUE TITLE
To do lists not showing

### ISSUE THREAD

**Issue by nikoandreop** [RogerSelwyn/O365-HomeAssistant#250]
I copy and pasted the sample config for the to do list card and restarted the card sometimes shows up with just the title and no tasks or it just doesn’t show at all. The calendar syncs and works. I am very new to home assistant. I am somewhat comfortable editing yaml code tho.Any ideas ?

**Comment by RogerSelwyn** [comment]
If you are after just ToDo, I would suggest using https://github.com/RogerSelwyn/MS365-ToDo, you need to add the repository to HACS, but that isn't hard. It will eventually replace O365.

If you want to continue with o365, have you looked at the system logs for any hints?

**Comment by RogerSelwyn** [comment]
No response, so closing
