### ISSUE TITLE
Hide Private Events

### ISSUE THREAD

**Issue by philjlihp** [RogerSelwyn/O365-HomeAssistant#253]
Just installed and seems to be working really well, thank you.
Two issues, I have. I dont seem to be able to add events to calendar from the home assistant calendar page and is it possible in the calendar config to exclude entries marked as private?

thanks

**Comment by RogerSelwyn** [comment]
Have you enabled updates? No private eyes are not currently supported. Please raise a feature request.

**Comment by philjlihp** [comment]
Ah ok, it's an all or nothing to write to calendars, sorted, thanks!
I'll see if I can figure how to raise a change request for the other. Thanks for creating this and for your help.

**Comment by RogerSelwyn** [comment]
Just edit this one with the details of what you are expecting to happen. Ideally validate that the information is available via ms graph explorer.

**Comment by RogerSelwyn** [comment]
I have added the functionality to the MS365-Calendar integration which will eventually replace the calendar element of O365.

https://github.com/RogerSelwyn/MS365-Calendar/releases/tag/v0.1.4b1
