### ISSUE TITLE
Cant create new App for the API token

### ISSUE THREAD

**Issue by mkrasselt1** [RogerSelwyn/O365-HomeAssistant#255]
When i follow the preparations link to microsoft azure application registration i get the following message:
`Starting June 30, 2020, we will no longer add new features to Azure Active Directory Authentication Library (ADAL) and Azure Active Directory Graph. We will continue to provide technical support and security updates, but we will not provide additional feature updates. Applications must upgrade to Microsoft Authentication Library (MSAL) and Microsoft Graph. [Learn more](https://go.microsoft.com/fwlink/?linkid=2132805)`

i understand that i cant create new applikations anymore, but it seams that i cant even get any app/api token anymore.
is that correct ?

**Comment by RogerSelwyn** [comment]
As long as you have a valid client id/secret it should work as far as I know. If you can’t create a new client id/secret pair then you will need to take that up with Microsoft.

**Comment by mkrasselt1** [comment]
so you are still able to create new apps?
because the message sounded like the discontinued these apps since 2020 all together - i will try something more, and mark this as closed if its just a problem with my account.

**Comment by mkrasselt1** [comment]
so it either asks me for a paid azure plan or that its impossible... i guess (we here in europe)  cant do anymore.. so not at all a problem here ...

**Comment by RogerSelwyn** [comment]
Others have had this problem if you look through past issues. I’m afraid I’m out at the moment so can’t search for it for you. It can be done with a developer account, but I have no control over it at all.

**Comment by mkrasselt1** [comment]
it seams one has to register for a free azure account first - not shure if it will stay for free but i am willing to try it out - may be todo is one of the "forerver free" services

**Comment by RogerSelwyn** [comment]
If you can provide me some details on what you have done, then I will try to provide an update on the docs.
