### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by Mbraad** [RogerSelwyn/O365-HomeAssistant#260]
Hello, been trying to set this up for quite some hours now. 
I am now stranded at this error, any idea what this could mean?  (bear i am pretty new i HA so might be a rookie mistake)

Logger: O365.connection
Kilde: /usr/local/lib/python3.12/site-packages/O365/connection.py:838
Første forekomst: 19.41.32 (1 forekomster)
Senest logget: 19.41.32

Client Error: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/me/chats?%24top=20 | Error Message: No authorization information present on the request. | Error Code:

THANKS for all the work!

**Comment by RogerSelwyn** [comment]
Please post the full error

**Comment by RogerSelwyn** [comment]
Also, are you using a personal or workplace account?

**Comment by RogerSelwyn** [comment]
To be honest, I would start with basic calendar setup, before you try anything else. Also I'd use the MS365 versions of the modules shown here, because o365 will be deprecated at some point.

https://rogerselwyn.github.io/MS365-Calendar/

**Comment by Mbraad** [comment]
Hello, dont know what happend, after posting here i restarted HA once more, and suddenly everything worked. YAY!

Thanks for quick repsponse!
