### ISSUE TITLE
HA Core Error on removal of integration

### ISSUE THREAD

**Issue by J3G3** [RogerSelwyn/O365-HomeAssistant#266]
On removing the O365 integration I receive these errors following any HA restart. 

Logger: homeassistant.setup 
Source: setup.py:269
2024-12-21 17:57:37.285 WARNING (MainThread) [homeassistant.helpers.translation] Failed to load integration for translation: Integration 'o365' not found.

Logger: homeassistant.helpers.translation
Source: helpers/translation.py:226
2024-12-21 17:57:40.648 ERROR (MainThread) [homeassistant.setup] Setup failed for 'o365': Integration not found.

Both adding and removing were performed through the HACS module
I tried re-adding and re-removing O365.  Errors stop when O365 is reinstalled, but reappear again on removal.  
I migrated to your M365 Calendar integration in case that has any bearing on issue

Also -- Thank you for maintaining the office integrations!

**Comment by RogerSelwyn** [comment]
Did you remove the o365 config from configuration.yaml?

**Comment by J3G3** [comment]
That worked - thank you!
