### ISSUE TITLE
Something odd in BST?

### ISSUE THREAD

**Issue by gingemonster** [RogerSelwyn/O365-HomeAssistant#30]
I have the following events in my calendar:

![image](https://user-images.githubusercontent.com/703352/160448588-7c67155f-6253-4d36-9783-84bd74e8914a.png)

Using a template on the developer tools I can get the following debug info:

UTCNOW for debug 2022-03-28 16:56:24.615267+00:00
Time now for debug 2022-03-28 17:56:24.615324+01:00

Calandar state's data attribute:

 [{'summary': 'Timezone test 2 OPS-11', 'description': '', 'location': '', 'categories': [], 'sensitivity': 'Normal', 'show_as': 'Busy', 'all_day': False, 'attendees': [], 'start': datetime.datetime(2022, 3, 28, 18, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 28, 18, 25, tzinfo=<UTC>), 'uid': 'REDACTED', 'calendar_id': 'REDACTED', 'subject': 'Timezone test 2 OPS-11', 'body': ''}, {'summary': 'OPS-11 test', 'description': '', 'location': '', 'categories': [], 'sensitivity': 'Normal', 'show_as': 'Busy', 'all_day': False, 'attendees': [], 'start': datetime.datetime(2022, 3, 28, 19, 0, tzinfo=<UTC>), 'end': datetime.datetime(2022, 3, 28, 19, 25, tzinfo=<UTC>), 'uid': 'REDACTED', 'calendar_id': 'REDACTED', 'subject': 'OPS-11 test', 'body': ''}
 
 You will notice the first entry in the calendar is "Timezone test 2 OPS-11" even though my calendar clearly shows the next event is ""Timezone test OPS-11"
 
I only noticed this today so assume its due to the British Summertime change on Sunday?

So even though I can see in the data that the events are pulling through with the correct UTC times it looks like the events are being filtered by the local time somewhere in the code removing the next upcoming event?

**Comment by RogerSelwyn** [comment]
I'll try to take a look tomorrow.  Just as a matter of interest what time zone are you in? And what time zone is your ha host in?

**Comment by RogerSelwyn** [comment]
Also what is the template you used on developer tools?

**Comment by gingemonster** [comment]
Hi Roger

Im in the UK so currently HA and Office365 are in BST. Template I am trying to use to debug this is:

```YAML
UTC {{ utcnow() }}
BST {{ now() }}
{{ states.calendar.MYCALENDARNAME.attributes}}
```

Generally I am really confused between how calendars handle the next event (show by the attributes in the root of the calendar state) and the other following events (shown in the data attribute as an array).

The two sets of data seem to update at different times and all day events seem to stay as the event in the root.

All of this seems to make it practically impossible to consistently get the next upcoming event (that's not an all day event)

**Comment by RogerSelwyn** [comment]
I’ve tried not to change the structure on what is provided on the sensor because of unexpected consequences. I’ll take another look at it and see what can be done. 

Sorry won’t be tomorrow, mother-in-law duties tomorrow.

**Comment by gingemonster** [comment]
not a problem thanks for looking at all, im doing further testing now to see if I can understand it better

**Comment by RogerSelwyn** [comment]
To be honest a lot of it is thinking about how it should look, then making it so. But I've done calendars before on another open source platform, and I hate time zones and DST, so I'm hoping it's a simple case of it using a utc date rather than local date to filter by. I fear though that the integration may not know ant the local date is, bearing in mind it is filtering server side rather than client side so can't know what the user time is. The HA calendar panel just shows everything for a month, so doesn't need to care, events are presented to it and utc, and it converts to user date time at display.

So, I need to look at the code again, and try and figure out how it knows what to filter on based on the fact that this could be being displayed in New Zealand as well...

**Comment by gingemonster** [comment]
Ok the below possible shows one thing going on to confuse me. Note in output sample below:

1) The "next" event in the root of the attributes is an event set at 20:00 BST, it's "start_time" attribute bolded below shows the BST time
2) The following events show their "start" attribute as UTC values, as they should do

==================================================

UTC 2022-03-28 19:08:05.528260+00:00
LOCAL TIME 2022-03-28 20:08:05.528309+01:00

OUTPUT FROM states.calendar.MYCALENDER.attributes

**{'message': 'TEST 20:00 BST'**, 'all_day': False, **'start_time': '2022-03-28 20:00:00'**, 'end_time': '2022-03-28 20:25:00', 'location': {'displayName': '', 'locationType': 'default', 'uniqueIdType': 'unknown', 'address': {}, 'coordinates': {}}, 'description': '', 'offset_reached': False, 'data': [{**'summary': 'TEST 21:00 BST'**, 'description': '', 'location': '', 'categories': [], 'sensitivity': 'Normal', 'show_as': 'Busy', 'all_day': False, 'attendees': [], **'start': datetime.datetime(2022, 3, 28, 20, 0, tzinfo=\<UTC\>)**, 'end': datetime.datetime(2022, 3, 28, 20, 25, tzinfo=\<UTC\>), 'uid': 'AAMkADgwZDk2YTBkLWRjYWQtNDc0MC04ODJlLTRmNjJmY2FlYTYzNQBGAAAAAADg-JhHpZp8Sb1SHLvnHbMTBwBTzNMcWKIsSak2Uwp-uMpgAAAAAAENAABTzNMcWKIsSak2Uwp-uMpgAAbwDjS0AAA=', 'calendar_id': 'AAMkADgwZDk2YTBkLWRjYWQtNDc0MC04ODJlLTRmNjJmY2FlYTYzNQBGAAAAAADg-JhHpZp8Sb1SHLvnHbMTBwBTzNMcWKIsSak2Uwp-uMpgAAAAAAEGAABTzNMcWKIsSak2Uwp-uMpgAAY2I7ouAAA=', 'subject': 'TEST 21:00 BST', 'body': ''}, {'summary': 'TEST 22:00 BST', 'description': '', 'location': '', 'categories': [], 'sensitivity': 'Normal', 'show_as': 'Busy', 'all_day': False, 'attendees': [], 'start': datetime.datetime(2022, 3, 28, 21, 0, tzinfo=\<UTC\>), 'end': datetime.datetime(2022, 3, 28, 21, 25, tzinfo=\<UTC\>), 'uid': 'AAMkADgwZDk2YTBkLWRjYWQtNDc0MC04ODJlLTRmNjJmY2FlYTYzNQBGAAAAAADg-JhHpZp8Sb1SHLvnHbMTBwBTzNMcWKIsSak2Uwp-uMpgAAAAAAENAABTzNMcWKIsSak2Uwp-uMpgAAbwDjS1AAA=', 'calendar_id': 'AAMkADgwZDk2YTBkLWRjYWQtNDc0MC04ODJlLTRmNjJmY2FlYTYzNQBGAAAAAADg-JhHpZp8Sb1SHLvnHbMTBwBTzNMcWKIsSak2Uwp-uMpgAAAAAAEGAABTzNMcWKIsSak2Uwp-uMpgAAY2I7ouAAA=', 'subject': 'TEST 22:00 BST', 'body': ''}

==================================================

This itself isnt causing the issue (other than confusing me) but does make me think you might be right and that the "data" attribute's entries are being filtered using the local time not utc

**Comment by RogerSelwyn** [comment]
I've been looking at code whilst watching Peaky Blinders... If I remember correctly I set it so that all events are passed back to the integration from O365 in UTC (it's a change I made last year because of a problem in the O365 access module), but I need to get into debug to validate what is happening.

**Comment by RogerSelwyn** [comment]
Just followed the code back and yes, it should be getting events back in UTC. It also looks like it is working on server local time to fetch events and to check if an event is finished.

`account = Account(credentials, token_backend=token_backend, timezone="UTC")`

I don't think this is difficult, just a matter of being careful when debugging. I think I'm surprised that people outside the UK haven't complained before.

I want to see if I can come up with a wizard wheeze to have the current non all day event show at the root, rather than any all day event, but still show the all day event if no current event.

**Comment by RogerSelwyn** [comment]
By the way for the time being you should be able to set the start offset to -1 and it should operate as before.

**Comment by gingemonster** [comment]
Turned on debug in the logs (starting to learn how this all works ;-) ) and i can see this request to the graph api:

```2022-03-28 21:20:41 DEBUG (SyncWorker_1) [O365.connection] Request parameters: {'params': {'$top': 999, 'startDateTime': '2022-03-28T21:20:41.458445+00:00', 'endDateTime': '2022-03-29T21:20:41.458460+00:00'}, 'headers': {'Prefer': 'outlook.timezone="UTC"'}, 'allow_redirects': True}```

To me at least that suggests that the code is requesting the dates using BST times but being told they are UTC times?

I modified the code below to explicitly convert the dates to utc:

```
    async def async_o365_get_events(self, hass, start_date, end_date):
        """Get the events."""
        _LOGGER.debug(
            "requesting O365 with dates",
            start_date,
            end_date,
            dt.as_utc(start_date),
            dt.as_utc(end_date)
        )        
        query = self.calendar.new_query("start").greater_equal(dt.as_utc(start_date))
        query.chain("and").on_attribute("end").less_equal(dt.as_utc(end_date))
        if self.search is not None:
            query.chain("and").on_attribute("subject").contains(self.search)
        return await hass.async_add_executor_job(
            ft.partial(
                self.calendar.get_events,
                limit=self.limit,
                query=query,
                include_recurring=True,
            )
        )
```
adding in a quick debug entry and that now seems to be sending requests in UTC

```2022-03-28 21:57:08 DEBUG (SyncWorker_10) [O365.connection] Request parameters: {'params': {'$top': 999, 'startDateTime': '2022-03-28T20:57:08.776406+00:00', 'endDateTime': '2022-03-29T20:57:08.776425+00:00'}, 'headers': {'Prefer': 'outlook.timezone="UTC"'}, 'allow_redirects': True}```

**Comment by RogerSelwyn** [comment]
Yep, that's what my code read says.  I'll get to it probably Wednesday.

**Comment by RogerSelwyn** [comment]
I think you'll also see the is_over method which supports what appears at the root, is also checking against now() instead of utcnow()

**Comment by RogerSelwyn** [comment]
I've posted a new alpha with changes which I think fix it, and also mean a non-all day event is put at the root in preference to an all day event.

https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v3.0.0a7

Or check the changes in this commit if you aren't using the 3.x versions yet.

https://github.com/RogerSelwyn/O365-HomeAssistant/commit/48fd0ef478e879df1c05bbb2449037cecfa71cb5

**Comment by RogerSelwyn** [comment]
Posted a new commit to refine which event gets put as root (which only selects from current day), plus make sure to_datetime returns a utc date.

Event selection is:
- Current event
- Current all day event
- Future event

**Comment by gingemonster** [comment]
Thanks will do some testing here and report back

**Comment by RogerSelwyn** [comment]
Note my comment on the forum, there is a breaking change coming in HA coming, which I have coded for in the committed 3.x codebase. I'll probably post a 2.x fix tomorrow.

**Comment by uSlackr** [comment]
Roger, thanks for all your work on this.  Question – could you link to the forum post you are tracking?  I’d like to track that too.

\\Greg

**Comment by RogerSelwyn** [comment]
It's linked from the home page of this repository 😀

https://community.home-assistant.io/t/office-365-calendar-access/154359

**Comment by uSlackr** [comment]
Oops!

\\Greg

**Comment by gingemonster** [comment]
@RogerSelwyn the new event selection logic appears to be working as described, is a little hard to test as the root even seems to update out of sync (and much slower). BST issues also fixed. Thanks for sorting all this has helped me finish updating one of my pet DIY projects 

https://www.reddit.com/r/homeassistant/comments/ts0y6a/got_round_to_converting_my_weasley_clock_to_be/

**Comment by RogerSelwyn** [comment]
So you understand how the root and data elements get updated. They are both 'updated' at the same time, i.e. the code logic all runs together.

- Root should show current/next event as I described before within the current day, so it won't show events for tomorrow.
- Data shows the events as defined by your start and end offsets. So if they are at the default 0 and 24, it would likely show All Day events first (since they start earliest and fall in the 0-24 hours from now period), then any other events in start order in the next 24 hours. If you were to set it to a negative offset it would show events in the past.

**Comment by gingemonster** [comment]
That is odd, when I view the data in the developer template tab I definitely see the root not updating in sync with the attributes when using a template like:

{{ states.calendar.my_calendar.attributes}} 

It looks like the data attribute events updates almost instantly yet the root event updates at most every 5ish minutes. Sure its nothing to do with this specific integration but perhaps something from the built in calendar code and not an issue just made testing tricky.

**Comment by RogerSelwyn** [comment]
I thought I had posted after your latest. Yes there is a 15 minute throttle on the root event, no idea why. The latest 3.x version removes the throttle - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v3.0.0a8
