### ISSUE TITLE
Last update 2022.4.0 Error

### ISSUE THREAD

**Issue by tbkon3** [RogerSelwyn/O365-HomeAssistant#35]
Version | core-2022.4.0
Home Assistant OS | 5.10.108

After the last update i receive this error:

Logger: homeassistant.setup
Source: setup.py:298
First occurred: 19:22:06 (1 occurrences)
Last logged: 19:22:06

Unable to prepare setup for platform o365.calendar: Platform not found (cannot import name 'calculate_offset' from 'homeassistant.components.calendar' (/usr/src/homeassistant/homeassistant/components/calendar/__init__.py)

**Comment by RogerSelwyn** [comment]
Have you upgraded to version 2.4.1? If not, please do so and confirm if you still have an issue.

**Comment by tbkon3** [comment]
> 

i'm trying to force to find update but i've only 2.4.0

## System Health

version | core-2022.4.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.9
os_name | Linux
os_version | 5.10.108
arch | x86_64
timezone | Europe/Rome

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4411
Installed Version | 1.24.3
Stage | running
Available Repositories | 1019
Downloaded Repositories | 95

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 46

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.6
-- | --
update_channel | stable
supervisor_version | supervisor-2022.03.5
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 25.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), Check Home Assistant configuration (3.10.0), Duck DNS (1.14.0), Let's Encrypt (4.12.0), Mosquitto broker (6.0.1), TasmoAdmin (0.17.0), deCONZ (6.12.0), Dropbox Sync (1.3.0), Home Assistant Google Drive Backup (0.106.2), ADB - Android Debug Bridge (0.8.0), FTP (4.5.0), File editor (5.3.3), Portainer (2.0.0), InfluxDB (4.4.1), Plex Media Server (2.8.0), SSH & Web Terminal (10.1.1), Frigate NVR (3.1), ESPHome (2022.3.1), Grafana (7.5.2), Xiaomi Mi Scale (0.2.8), Studio Code Server (4.2.0), AppDaemon (0.8.2), Network UPS Tools (0.10.0), Vaultwarden (Bitwarden) (0.16.0), Grocy (0.17.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 81
views | 15
mode | yaml

</details>

**Comment by RogerSelwyn** [comment]
You need to upgrade the O365 integration to 2.4.1 not HA (which is at 2022.4.0)

**Comment by RogerSelwyn** [comment]
https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v2.4.1

**Comment by tbkon3** [comment]
> https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v2.4.1

perfect, it's working, thank you!!!
