### ISSUE TITLE
Notify Service Enable/Disable Toggle

### ISSUE THREAD

**Issue by thatdoogieguy** [RogerSelwyn/O365-HomeAssistant#36]
Hi Roger,

Is there an enable/disable capability for the notifier service? I use a number of notification targets and love this component but am struggling to effectively disable the notification part? Silly question I am sure!

**Comment by RogerSelwyn** [comment]
You can set enable_update to False which will disable all the services.

https://github.com/RogerSelwyn/O365-HomeAssistant#configuration-variables
