### ISSUE TITLE
Invalid config error - yamllint indicates no error

### ISSUE THREAD

**Issue by sunishnet** [RogerSelwyn/O365-HomeAssistant#38]
Invalid config for [o365]: [accounts] is an invalid option for [o365]. Check: o365->o365->accounts. (See /config/configuration.yaml, line 86).

What could be the issue ?

Installation was done using hacs download.

**Comment by RogerSelwyn** [comment]
I imagine you have installed v2.4.1 from HACS. That structure of config is only for v3.x. I've added a note to the Readme. If you want to use v3.x then enable beta versions for O365 within HACS.

**Comment by sunishnet** [comment]
yes, the manifest indicates v2.4.1, will try v3.x.

Thanks

**Comment by sunishnet** [comment]
On 3.x no error in config file, but I did not get any persistent notification for authentication/default auth flow even after restarting HA multiple times and no error message

**Comment by RogerSelwyn** [comment]
Yes, it means you haven't authenticated (which you need to to before you get any calendars), unless you think you have.

**Comment by RogerSelwyn** [comment]
Or are you saying you didn't get a notification?  Have a look under notifications in the menu, because I suspect the notification is there, it's just the menu item isn't getting a badge.  If the notification isn't there, setting the logging level to info at maximum, and see if anything is shown in the logs.

**Comment by sunishnet** [comment]
There was error due to mistake in yaml. Fixed it but failed with Azure authentication as I don't have https at the localenpoint. I have port forwarding issue with my ISP so can't get Letsencrypt certificate 
Failed with message:
AADSTS50011: The redirect URI 'http://192.168.0.200:8123/api/o365' specified in the request does not match the redirect URIs configured for the application.

At least from the App perspective, I think this issue can be closed as its working as mentioned in the documentation

**Comment by RogerSelwyn** [comment]
Use the alternate method of authentication. It needs no direct access to you HA instance.
