### ISSUE TITLE
No ability to see O365 Group calendars

### ISSUE THREAD

**Issue by loryanstrant** [RogerSelwyn/O365-HomeAssistant#40]
It would be very handy if there was a way we could add M365 Group calendars into this as well.
I tried to be smart and add a Group calendar directly into the calendars.yaml file using the calendar ID, but I didn't realise that the Graph lookup is using the /me endpoint - which wouldn't show a Group calendar:
![image](https://user-images.githubusercontent.com/51473494/165064409-9ecb4c2f-6547-4bb7-b191-4292ed422347.png)

What we would need instead is to have a Graph lookup that uses the Group ID and looks more like this:
https://graph.microsoft.com/v1.0/groups/{group-id}/calendar
That gives us the calendar ID.

However, to look up events, we can just use https://graph.microsoft.com/v1.0/groups/{group-id}/events.

I couldn't see a direct way to access the connection.py in the error so didn't know how to add this in myself.

**Comment by RogerSelwyn** [comment]
I'll take a look, but I'm not able to spend much time on the computer due to a back problem at the moment. The integration uses this module, so it's a case of figuring out if that has the functionality to support group calendars, which I'd expect it does.

https://pypi.org/project/O365/

**Comment by loryanstrant** [comment]
Thanks Roger. Sorry to hear about your back.
That project does support Groups: https://github.com/O365/python-o365/blob/master/O365/groups.py
It doesn't have the endpoint for the calendar or events listed though.

While I'm not a dev, I do know my way around Graph. Is there anything I can do while you're resting to start having a crack at this (whether in your repo or theirs)?

**Comment by RogerSelwyn** [comment]
This is a clue - https://github.com/O365/python-o365/issues/441 - so it suggests it is possible. From the code clues, I guess the resource mentioned in there is the group guid, from which the list of calendars for the group can then be retrieved. Not sure if there is a way to use a user friendly name to find the group guid, something that could be used more easily in the config - I.e. something a standard user would know, rather than an admin

**Comment by loryanstrant** [comment]
The Group ID does show up in a variety of places, like a Teams channel URL in the browser, as well as a few others. So it's not beyond the reach of the average user to retrieve without being an admin. However, that being said, this solution requires admin access to the tenant in the first place, so... :-)

Given your solution uses that module, does that mean something *could* be done with what's available today?

**Comment by RogerSelwyn** [comment]
The code shown in the linked issue says it can be done. Might take me a few weeks though...

How do you create a group mailbox/calendar? I've created shared ones, which to be honest I don't think I had to do anything special to access when the right permissions were given. Sorry, but it's been 20 years since I played with Exchange in any seriousness, and I only do what I must via the admin interface. For guidance, I have my own domain name where mail is host on 'Exchange Online' (or was), with 3 user mailboxes and a number of shared mailboxes.

**Comment by loryanstrant** [comment]
All good. So an M365 Group can be created in a TON of different ways, which results in the mailbox/calendar being created.
For some fun reading, I wrote this doc for Microsoft a couple of years back that outlines the different ways a Group can get created: https://docs.microsoft.com/en-us/microsoft-365/solutions/groups-services-interactions?view=o365-worldwide

So there's a ton of different ways an end-user can create a Group, although I hardly see people using the calendar of the group (which is disappointing).

To be honest, my particular requirement here, is that as a Microsoft MVP I have a free M365 tenant and licenses - so my household all has mailboxes, OneDrives, etc. Talking with my wife, we were trying to figure out how to display a family calendar in HA that has all our shared family events, and her suggestion (she's also a MS MVP who specialises in M365) is that we use a Group as it gets the calendar. As we already have one set up for our shared files and emails via DL, it made logical sense.

So, given that specific requirement - if it's not worth the hassle to make work, I completely get it and I can look at an alternative method. :-)

**Comment by RogerSelwyn** [comment]
I think if you create a shared mailbox, and put a calendar in that and give everyone access, it will show.  Not 100% sure, but I think I tested it when I removed the requirement for shared permissions.

**Comment by loryanstrant** [comment]
Ok, will give that a go now and let you know. Thanks

**Comment by RogerSelwyn** [comment]
They should update every minute. It should automatically get added to calendars.yaml, but to get that to happen I had to go into O365 online and add a calendar from directory. Then restart HA or run scan for calendars service. 

You may be able to do the same thing on Outlook on a PC, but I have a Mac Outlook and I couldn't see how to do it there (all though it now shows in my list of calendars under my main O365 account.

**Comment by loryanstrant** [comment]
Thanks, but I've already got the calendar showing up successfully. I'm just not seeing any events coming through despite me putting some in.
I'll head to bed now and see if it shows up tomorrow.

Thanks

**Comment by RogerSelwyn** [comment]
Maybe it needs the shared permissions. I'll try to check that out.

**Comment by loryanstrant** [comment]
I did pre-emptively add that to my app registration though. Will report back in the morning.
________________________________

***@***.*** 983 666
www.strantconsulting.com

**Comment by RogerSelwyn** [comment]
OK, so I granted permissions from the Ty'r Celyn shared mailbox for me to access the calendar (I granted Owner, but probably didn't need that much). This is what I get below depending on where I create the event from:

<img width="1004" alt="Screenshot 2022-04-25 at 14 22 31" src="https://user-images.githubusercontent.com/7115783/165099088-386f7f35-1c73-4e74-86bb-ebf96beed12f.png">

So if event is created from under my user account I can see it under my user account and in HA. If it is created under the Ty'r Celyn account I can't see it anywhere else. These are the permissions granted, firstly from the Ty'r Celyn account, then as visible from my account. I'm guessing it is some sort of permissions problem.

<img width="484" alt="Screenshot 2022-04-25 at 14 32 04" src="https://user-images.githubusercontent.com/7115783/165099527-8e8ac3e8-d82d-4f03-a250-53e9b78942ad.png">
<img width="536" alt="Screenshot 2022-04-25 at 14 32 24" src="https://user-images.githubusercontent.com/7115783/165099611-431e099d-fe94-4f96-8d9a-9494030a3780.png">


Whilst I did also grant shared calendar permissions in the Azure App, removing them again doesn't seem to have removed access to the events.

**Comment by loryanstrant** [comment]
Interestingly, as it's Graph permissions, whatever you set in Outlook shouldn't matter.
I'll try to do some direct Graph queries tomorrow to see if I can see the items, which will help determine the cause of the missing items.
________________________________

***@***.*** 983 666
www.strantconsulting.com

**Comment by loryanstrant** [comment]
Spoke too soon.
Appears to have worked as I'm not seeing an entry in HA.
Will try again tomorrow and see roughly how long it takes to show up.
________________________________

***@***.*** 983 666
www.strantconsulting.com

**Comment by RogerSelwyn** [comment]
I happened to look this morning and noticed that event 'Test TC 4' was now appearing in HA and twice in my Outlook calendar, so at some point in the last 18 hours it seems to have synced up.

**Comment by loryanstrant** [comment]
I've just created a couple of appointments right now, so will see if they appear in the next 5 hours before I go to bed.

Thanks


***@***.*** 983 666
www.strantconsulting.com

**Comment by RogerSelwyn** [comment]
In the image of Outlook above, the event created via my O365 account (top) appeared in the Ty'r Celyn account within minutes and within HA. The reverse direction, took some time, I wasn't watching so it may have been hours. Not sure how long they would take to appear in another users account, didn't check that.

**Comment by RogerSelwyn** [comment]
Closed as stale.
