### ISSUE TITLE
O365 re-link required every time I restart HA

### ISSUE THREAD

**Issue by GitHubGoody** [RogerSelwyn/O365-HomeAssistant#41]
I'm configured using the default auth flow. It was working well for a couple days, but now I get prompted by the configuration notification each time I restart HA. Each time, I login to my Office 365 account, but the request to accept the integration does not appear...it just closes the tab and my calendar works again. Is there something I can do to reset this handshake properly to stop the nuisance notifications?

**Comment by RogerSelwyn** [comment]
I've not seen this problem at all (bear in mind I only took this integration on to keep it alive originally) but the implication is the authentication token is going invalid or is being deleted at each reboot. You can check the token, which is located in the .O365-token-cache folder, is present after a restart.

Other than that I'd re-create the Azure App from scratch, making sure you don't set any short expiry dates (I'm sure I've seen one asked somewhere), and probably use the alternate auth path (to be honest it's simpler).  

Also you can turn on debug logging for the integration `custom_ components.o365: debug` will do it. If it can't find a token file, it will tell you in the logs.

**Comment by GitHubGoody** [comment]
> I've not seen this problem at all (bear in mind I only took this integration on to keep it alive originally) but the implication is the authentication token is going invalid or is being deleted at each reboot. You can check the token, which is located in the .O365-token-cache folder, is present after a restart.
> 

No problem and thank you for keeping this going. I'm assuming this happened because I initially set the app up, deleted it from HACS, then reinstalled it.

I poked all around the directories and couldn't find that folder (even after a good re-sync). I'm definitely not seeing it under config/custom_components/o365. What's the full path of where I should be looking for the token?

Alternatively, I was thinking there might be an Office 365 site where I could disapprove the previously approved integration allowing the configuration to actually complete on a subsequent restart. Any thoughts there?

> Other than that I'd re-create the Azure App from scratch, making sure you don't set any short expiry dates (I'm sure I've seen one asked somewhere), and probably use the alternate auth path (to be honest it's simpler).
> 

I definitely set it to 2 years. It's not clear to me the pros/cons of each auth path, but if I cannot get the default one stable, I'll go down the alt path.

> Also you can turn on debug logging for the integration `custom_ components.o365: debug` will do it. If it can't find a token file, it will tell you in the logs.

Do I just put this in configuration.yaml?

**Comment by RogerSelwyn** [comment]
The token folder is in the root of your config folder. Depending on how your accessing your system, the '.' on the start will make it a hidden folder. You can go through on the azure app and delete all the permissions, but probably easier to delete and re-create.

You need the debug under logger in your config.yaml. 

```
logger:
  custom_components.o365: debug
```

**Comment by GitHubGoody** [comment]
Found it, thanks. The tokens from the initial and current installation were both there. Then I deleted the old one and took note of the modified time on the current token. Also, I peaked at my calendar card and there were no events. The notification to re-sync was there in notifications, so I did that again and the token's modified time updated and (after reloading the page), the events populated on the calendar card. So, it does seem like the token is no longer valid on a restart.

I went ahead and deleted then recreated an Azure app. Sure enough, this time I was presented with the request to authorize the integration. But, after a restart, I'm still getting prompted to configure the integration.

Here is what the logs contained:
https://portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade

Also, there was this notification on Azure when I just logged back in to check on that Presence.Read warning (which I don't understand since that permission IS set):
![image](https://user-images.githubusercontent.com/46235745/165189193-719fc434-2bc3-4dac-843d-e50213ad7626.png)

**Comment by GitHubGoody** [comment]
I saw this too

https://github.com/PTST/O365-HomeAssistant/issues/46

**Comment by RogerSelwyn** [comment]
The O365 error you listed above suggests that the user you are authenticating with (from live.com) isn't a user that exists in the AD for the azure app you created. I.e. the Azure App is in a tenant with access to the user accounts for contoso.com, and you are trying to authenticate with joe.bloggs@live.com.

I'd need to validate that in the morning, it is 4am here, trying to authenticate with a Hotmail account. Not sure where to check in Azure interface to find those errors though....

**Comment by RogerSelwyn** [comment]
When I link via my personal account (which has the same email address as my O365 tenant accounts, then I see the errors you are reporting. If you look at the token, I think you will find presence.read is not listed in there (though it will have been requested), and I suspect when the dialogue came up asking you to grant permissions (which it only does the first time) that it didn't have a request for Presence permission. I would imagine this is because a personal account doesn't have access to Teams.

I believe the errors are because the personal account does not have access to my tenant account mailbox. So the token is created because someone logged in, but it gets loads of errors because it doesn't have access.

So, when I properly log out off my Microsoft account, and delete the token and after deleting the link to the app from my personal account, then try to relink, it offers me the chance to log into my work account or my personal account. When I login with my work account, it works fine.

I did find after testing it this morning that I think it had changed the calendar ids in calendar.yaml. So I deleted the entries in there , and it recreated them fine.

**Comment by GitHubGoody** [comment]
> The O365 error you listed above suggests that the user you are authenticating with (from live.com) isn't a user that exists in the AD for the azure app you created. I.e. the Azure App is in a tenant with access to the user accounts for contoso.com, and you are trying to authenticate with [joe.bloggs@live.com](mailto:joe.bloggs@live.com).
> 
> I'd need to validate that in the morning, it is 4am here, trying to authenticate with a Hotmail account. Not sure where to check in Azure interface to find those errors though....

The personal account I'm trying to connect with is our family xyz@outlook.com account, but I also have an individual personal account abc@live.com. Of course, when logging into the O365 authentication, I'm using the xyz@outlook.com account, so I'm not sure why it's picking up on my abc@live.com account.

**Comment by RogerSelwyn** [comment]
I don’t think just deleting the presence element will solve it because you are getting errors for your inbox, which is the type of error I had as well.

**Comment by GitHubGoody** [comment]
Thanks, I tried Chrome, but it didn't change the results.

I posted on the Azure community here (https://docs.microsoft.com/en-us/answers/questions/827017/noob-trying-to-connect-to-office-365-personal-acco.html). Did I get the description of my problem and what I need right?

Above, I think I made my final edits while you were replying, but for Step 3, where/how do I do this? Is it somewhere under my Microsoft account? Do I have the correct steps based on what you know at this point?

**Comment by RogerSelwyn** [comment]
If you mean how do you delete the token, just delete the token file. But I would also actually delete the app and recreate, so you know everything is gone. As far as my experience goes, I'm pretty sure you don't need to add the permissions to the app on Azure, when you authenticate it will add them and then you should see them on the app console. When the dialogue box comes up to approve them, there is a tick box to approve them for the enterprise (or something like that), I always tick that. That said, I didn't create the integration initially, so there may be a reason why the creator said add the permissions up front.

**Comment by GitHubGoody** [comment]
I know how to delete the token. I was asking about the step you mentioned to "delete the link to the app." I don't know exactly what you mean by this, but I'll try to delete the Azure app again. I'm not not sure what I'll be doing different that the previous attempt though.

I do see all 8 required permissions under 'API permissions' which match what I set IAW this integration's setup instructions (as you mention at the end).

I don't recall seeing a tick box, so I'll pay careful attention and look for that on this next attempt.

What are your thoughts on the first reply here?
https://answers.microsoft.com/en-us/msoffice/forum/all/noob-trying-to-connect-to-office-365-personal/c37dcb24-3dfc-491b-af58-24296fd2000f

**Comment by RogerSelwyn** [comment]
When I authenticated using my personal account, I had an email telling me so, which then gave me a link to somewhere in MS land that allowed me to delete it. I'd imagine if you delete the app, it will remove any incorrect link up. 

With regards the response on your post, sorry it has me lost (as you may gather), I really don't know why your live.com account is being used when trying to access an outlook.com account. 

To be honest, I don't even know if this integration works with an outlook.com email address, I'd expect it to work with a specific domain name such as contoso.com, where you are the admin for the tenant for the whole domain when you set the app up.

**Comment by GitHubGoody** [comment]
Using Chrome exclusively, I just deleted the Azure app and followed the O365 integration instructions exactly. Of note, even after deleting the Azure app, logging out and back into Azure, I was still getting the authentication notice on Azure re: the live.com account (I was definitely not logged in with that account anywhere on Chrome). Strange.

After a couple of HA restarts, I'm still getting the persistent notification each time.

I never saw the enterprise tick box you mentioned. Here's the screenshot of that dialog:
![O365Authentication](https://user-images.githubusercontent.com/46235745/165403323-81d91596-7115-4cd4-9443-b7207e11ecf3.PNG)

**Comment by RogerSelwyn** [comment]
I just went through and created a new outlook.com email address and then logged in to azure app registration. I get exactly the same notification when I log in, down to the same tenant and app ids. It says live.com because the outlook.com email addresses are hosted by live.com. The tenant id given is Microsoft Services AAD tenant id. Which I guess an outlook email address doesn't have access to, or at least not a free one and I don't intend to pay to upgrade to Microsoft 365.

**Comment by RogerSelwyn** [comment]
It seems presence sensor is not supported by a personal account, so because it can't get that permission it is asking for it again every reboot. Just remove the presence sensor from your config.

For the Test_Inbox error, that looks like you have configured it wrong. Does the name have an underscore in it? If you try without the folder config value, it will just get the inbox. I configured the below, and it worked fine:

```
      email_sensor:
        - name: inbox
          folder: "Inbox/Test Inbox"
          max_items: 2
          download_attachments: False
```

**Comment by GitHubGoody** [comment]
Victory! I removed the user.presence setting on Azure and then commented out the folder (under query_sensor per the repo setup instructions) and status_sensor lines:

```
accounts:
  - account_name: xyz
    client_id: !secret office365_clientid
    client_secret: !secret office365_secret
    enable_update: True
    track_new_calendar: True
    email_sensor:
      - name: inbox
        max_items: 2
        is_unread: True
        download_attachments: False
    query_sensors:
      - name: "HA Notifications"
        # **folder: "Inbox/Test_Inbox"**
        from: "xyz@outlook.com"
        subject_contains: "Notification from Home Assistant"
        has_attachment: True
        max_items: 2
        is_unread: True
    **# status_sensors:
    #   - name: "User Teams Status"**
```
After a restart, the persistent notification is gone and the calendar is working!

Thank you! I'd like to share what we've learned in the readme, so I forked it and will submit a PR with my changes.

**Comment by RogerSelwyn** [comment]
It looks like you just copied my example config from GitHub. I suspect you don't need the query sensor, unless you think you are going to get mails with the subject `Notification from Home Assistant` that have an attachment and are unread.

For the mailbox, the minimum you need is as below. Anything else just restricts what you get in the sensor entity.

```
    email_sensor:
      - name: inbox
```
