### ISSUE TITLE
`CalendarEventDevice` is deprecated

### ISSUE THREAD

**Issue by IceBotYT** [RogerSelwyn/O365-HomeAssistant#43]
With the latest 2022.5 beta, a new message appears upon Home Assistant startup:
`CalendarEventDevice is deprecated, modify O365CalendarEventDevice to extend CalendarEntity`.

**Comment by RogerSelwyn** [comment]
Yes, I have it in hand 😀

**Comment by uSlackr** [comment]
Thanks for all your efforts on this.  Any way we can "buy you a coffee"?

**Comment by RogerSelwyn** [comment]
I have a buy a coffee link on my SkyQ repository.  I'm still learning this one, so haven't put a link on here yet 😀

**Comment by RogerSelwyn** [comment]
> Yes, I have it in hand 😀

I should add, I don't believe you will have a problem upgrading to 2022.5 because it is only a warning, but the 3.1.x releases will requires 2022.5 because they will include the change to remove the warning.

**Comment by uSlackr** [comment]
> I have a buy a coffee link on my SkyQ repository. I'm still learning this one, so haven't put a link on here yet 😀

You've done ALOT.  Post the link!!!

**Comment by RogerSelwyn** [comment]
Done :-)

**Comment by uSlackr** [comment]
And done!
