### ISSUE TITLE
Accessing the attributes of future events

### ISSUE THREAD

**Issue by GitHubGoody** [RogerSelwyn/O365-HomeAssistant#44]
I'm hoping this is an easy one and I just don't know the right syntax. I'd like to be able to search all of the events on my calendar for use in scripts.

I know this works to see the Subject (or any field) of the current/first event:
`{{ states.calendar.calendar_freakfam.attributes.message }}`

But, how do I access the data stored for the rest of the events?

[Extra motivation](https://media2.giphy.com/media/xUPGcmvgjMIEhy6jZu/giphy.gif?cid=ecf05e47lt1lfqjzwvk7590ctu5vmejyun8srqa5ch3krl3l&rid=giphy.gif&ct=g) (because I also couldn't figure out how to embed a gif ;-))

**Comment by RogerSelwyn** [comment]
You need to access the data attribute, which is an array, so I'd expect something like ...attributes.data[0]. But I don't use HA native capabilities in the most part, I use Node Red, which has fairly simple mechanisms for working through arrays. I'm afraid I don't know how to script it in HA native.

**Comment by GitHubGoody** [comment]
Yes! 2 for 2 today. Thanks!

`{{ states.calendar.calendar_freakfam.attributes.data[0...n] }}`

**Comment by uSlackr** [comment]
I'm finally giving this a go.  I have five calendars tied to my account and they can be see here:
![image](https://user-images.githubusercontent.com/25751399/165665231-2901a171-d878-4be9-8b0e-5ab214c2f0ad.png)

While there is data on the Family room as well as US Holidays, only the US Holidays has a full data attribute.
![image](https://user-images.githubusercontent.com/25751399/165664716-0c61fc95-7721-45fc-933f-7bc1c2f8cf6a.png)

**Comment by RogerSelwyn** [comment]
You would need to post your calendars.yaml to assist with identifying the problem. Please remove the calemdar_ids from any post.

**Comment by RogerSelwyn** [comment]
Also, what the time is for the event that is not showing. My guess is that it does not fall within the window configured for the calendar, which is what controls what appears on the data attribute.

**Comment by uSlackr** [comment]
OK.  I increased the `end_offset` and started seeing entries.  
I still have things to learn...
Thank you
