### ISSUE TITLE
"I authorized successfully" does nothing after successfully performing "Link Account"

### ISSUE THREAD

**Issue by jdiegmueller** [RogerSelwyn/O365-HomeAssistant#49]
Hello!  I have two Office 365 accounts I am trying to interact with.  "Account Tne" was able to successfully authenticate & pull down a token & works but "Account Two" does not -- hoping to get a hand with this.

I do get the configurator entity/Notification requesting authentication for Account Two, but after a successful authentication nothing happens (the window even stays open) and no token is ever written to .O365-token-cache/ for Account Two.

Both Account One and Two have MFA.  I only required the single Web RedirectURI for Account One.  Based on the comment in the README, I did add "https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize" as a second Web Redirect URI but still see the same "nothing happens" behavior.

I've tried cranking up logging to see if anything interesting happens, but even at DEBUG level I don't see any entries so I'm not quite sure what is (or isn't) happening.

Would love any pointers or suggestions to try.

Thanks!

**Comment by RogerSelwyn** [comment]
Try adding the below to your logger, this will add debugging of the actual module (not written by me) that calls O365. All HA integrations work this way (or should if they follow standards), they use a separate module to do the interface to the device/service they are working with.

`O365: debug`

Also, have you tried swapping the order of the accounts? And do they both use the same Azure App, or separate ones? I'm not sure I have tested with separate apps (client id/client secret).

I don't have MFA switched on with my accounts, so I'd have to see how much a mess it makes of my logons if I enable it.

**Comment by jdiegmueller** [comment]
A-ha!  Will try O365: debug now (was using custom_components.o365: DEBUG).  I'll also try reversing the order of the accounts and see if that changes which one doesn't work.  And if that doesn't work, perhaps I'll try the alternate authorization flow.

Your question about same or different Azure apps makes me think perhaps this might not be supported yet, so I better explain my scenario:   These are two completely different Office 365 tenants, not just two different accounts inside of a single Office 365 tenant.  So these are different applications, different client_ids, different client_secrets, etc.  

I'd love to disable MFA on Account Two, but unfortunately that's out of my control.  I'm the Office 365 administrator of Account One, but I'm just a regular user with regards to Account Two.

Thanks, I'll try the things I mention above now.

**Comment by RogerSelwyn** [comment]
With `custom_components.o365: debug` logging you should get the following messages through a successful authentication:

```
2022-05-06 14:25:29 WARNING (MainThread) [custom_components.o365.utils] Could not locate token at /home/Hassio/dev-config/.O365-token-cache/o365_Clare.token
2022-05-06 14:25:29 WARNING (MainThread) [custom_components.o365] No token, or token doesn't have all required permissions; requesting authorization
2022-05-06 14:27:16 INFO (SyncWorker_2) [custom_components.o365] Succesfully authenticated
```

**Comment by jdiegmueller** [comment]
I defintely get the "can't find token" bit, but I do not get any output at all (even with O365 at DEBUG) when trying to authenticate -- not "Successfully authenticated" nor anything indicating a failed authentication.

I tried commenting out my working account so that I am only dealing with the single Office 365 tenant & account, but still see the same behavior.  Clicking "Link Account" after a successful authentication from my browser simply does nothing, and nothing shows up in my log.  I don't know if I should or not at this stage, but I also see nothing in my reverse proxy server logs (ie, nothing is trying to hit my Web Redirect URL).

Going to try the alternate authentication flow, now, and see what happens.

**Comment by RogerSelwyn** [comment]
> Your question about same or different Azure apps makes me think perhaps this might not be supported yet, so I better explain my scenario: These are two completely different Office 365 tenants, not just two different accounts inside of a single Office 365 tenant. So these are different applications, different client_ids, different client_secrets, etc.

I think it should work, but I only have one very small tenant for my family accounts. So I haven't been able to test.

I'd try getting the second one working since that is likely the more complex. I don't know all the limits of what can be done because I don't own the O365 module, and I didn't write the original integration (though I've done a lot of work on it now).

If you get the successful authentication message back, it should be OK. It's not actually my code that writes the token, (though it does check against it for permissions), it is the O365 module that does that.

**Comment by RogerSelwyn** [comment]
I assume you are using alt_auth = True?

**Comment by jdiegmueller** [comment]
> I assume you are using alt_auth = True?

I haven't tried that, yet, no.

**Comment by RogerSelwyn** [comment]
Life is much easier using that method....

**Comment by RogerSelwyn** [comment]
But I'll re-test with False

**Comment by jdiegmueller** [comment]
Ok, we're getting somewhere with alt_auth_flow.  

The URL returned after successful authentication contains an error and an error description:
error=invalid_request&error_description=AADSTS50194%3a+Application+%27REDACTED_APP_ID%27(HomeAssistant+O365+integration)+is+not+configured+as+a+multi-tenant+application.+Usage+of+the+%2fcommon+endpoint+is+not+supported+for+such+applications+created+after+%2710%2f15%2f2018%27.+Use+a+tenant-specific+endpoint+or+configure+the+application+to+be+multi-tenant.

I changed it to multi-tenant, but now get the following (I see the same warning on the Azure configuration portal):
error=invalid_request&error_description=AADSTS50194%3a+Application+%27REDACTED_APP_ID%27(HomeAssistant+O365+integration)+is+not+configured+as+a+multi-tenant+application.+Usage+of+the+%2fcommon+endpoint+is+not+supported+for+such+applications+created+after+%2710%2f15%2f2018%27.+Use+a+tenant-specific+endpoint+or+configure+the+application+to+be+multi-tenant.

Any idea how I can spin up a tenant-specific endpoint?

**Comment by RogerSelwyn** [comment]
Same error both times?

**Comment by jdiegmueller** [comment]
Yes, identical.  

However in the Azure AD portal, I see the following when I change to multitenant ("Accounts in any organizational directory (Any Azure AD directory - Multitenant)"):
`"Starting November 9th, 2020 end users will no longer be able to grant consent to newly registered multitenant apps without verified publishers.  [Add MPN ID to verify publisher](https://portal.azure.com/#)"`

On the working Office 365 tenant/account, I have the following chosen -- unfortunately, this one isn't a choice on the non-working tenant/account):
`"Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)"`

**Comment by RogerSelwyn** [comment]
I have the first message on my dev App which I re-create all the time, so shouldn't really be an issue, but I'm not 100% sure.

Mine looks like this:
![Screenshot 2022-05-06 at 16 05 53](https://user-images.githubusercontent.com/7115783/167160603-6243989b-8565-4c37-839d-f6accf599b73.png)

For the account type, what did it offer?

Did you set your redirect uri for alternate auth?
![Screenshot 2022-05-06 at 16 09 25](https://user-images.githubusercontent.com/7115783/167161051-cdd86d2c-ddde-4268-8c08-1da80ab035f1.png)

**Comment by jdiegmueller** [comment]
Ok, I deleted and recreated the application and this time was able to choose "Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)".  I'm getting further, now during login I'm getting a pop-up which tells me that I require admin consent due to the permissions delegated:
```
Approval required
unverified
This app requires your admin's approval to:

Maintain access to data you have given it access to

Sign in and read user profile

Send mail as a user

Have full access to user calendars

Read user mail

Read user's presence information
```

I'm roughly 99.999% sure this customer won't grant me said permissions.  I'm happy to drop back to read-only with enable_update: false, but reviewing these permissions list above it appears even read-only will trigger this same requirement.

Are you aware of any way to make this go for just my account without requiring admin permissions?  If not, I will request permission and if denied I guess I'll just have to live with it.

**Comment by jdiegmueller** [comment]
I see under "Endpoints" that there do appear to be tenant-specific URLs for OAuth2 authorizatoin and tokens.  

I see in const.py we have the following:
`AUTH_CALLBACK_PATH_ALT = "https://login.microsoftonline.com/common/oauth2/nativeclient"` 

Could I perhaps recreate my app with "Tenant only" and then modify this to point one of the tenant-specific endpoints?  I don't see one that ends in "nativeclient" but I do have the following v2.0 endpoints:
* https://login.microsoftonline.com/TENANT_ID_REDACTED_BY_ME/oauth2/v2.0/authorize
* https://login.microsoftonline.com/TENANT_ID_REDACTED_BY_ME/oauth2/v2.0/token

And the following v1.0 endpoints:
* https://login.microsoftonline.com/TENANT_ID_REDACTED_BY_ME/oauth2/authorize
* https://login.microsoftonline.com/TENANT_ID_REDACTED_BY_ME/oauth2/token

**Comment by RogerSelwyn** [comment]
f you set `enable_update: False` it shouldn't request update access. Also, try and add the permissions to the app via the Azure console. I haven't dug into how they interact. If you follow the instructions on the integration readme they will end up in the top section. If you just allow the app to request permissions, and you approve them, they will appear at the bottom. Both seem to work.

<img width="1113" alt="Screenshot 2022-05-06 at 16 26 08" src="https://user-images.githubusercontent.com/7115783/167163805-7cd6087c-a6cd-44eb-b0e1-c520f83d014b.png">

Sorry, sciatica kicking in, I need to get up and move around. I may try and create an app via my wife's account later/tomorrow, where she doesn't have admin permission and see what it allows. However my tenant probably isn't as locked down as yours may be.

**Comment by jdiegmueller** [comment]
Since I'm admin on Account One I was able to grant the permissions directly from the Azure portal (and I have the nice green checkmarks for each).  But on Account Two I cannot, so I was hoping I could grant the permissions as part of the login/authentication process for my user only.  It appears not, though, as I still get the admin consent request pop-up even though the Azure portal says admin constant is not required:
![image](https://user-images.githubusercontent.com/18660571/167165496-ba24a8ca-d066-441b-bc85-7385383f86da.png)

Based on this, it appears to me like my only option is to request permissions for my user as part of the login process.  As I said I'm quite certain it will be denied, so perhaps there's simply no other options for me with regards to this account.

I'll submit a permission request and see what happens.  

Thanks so much for your help.

**Comment by RogerSelwyn** [comment]
On the pop-up I normally tick the box asking for permissions, but of course I am admin, so not a problem. As I said you can cut back the permissions to read only if that will help. I'll give it another go when my back has chilled a bit.

**Comment by RogerSelwyn** [comment]
OK, leg stretched.

If I create the app with my wife's account, add uri and secret then when I login with her account I get the following permissions on the app:
<img width="1169" alt="Screenshot 2022-05-06 at 16 53 52" src="https://user-images.githubusercontent.com/7115783/167169037-948f1e66-c4db-489e-afa1-c4a69fa1df6a.png">
This is the dialogue I get:
<img width="462" alt="Screenshot 2022-05-06 at 17 03 02" src="https://user-images.githubusercontent.com/7115783/167170166-b3476639-48fc-4fd0-bd7f-892c1436e2c7.png">

But also against the user in Azure AD, I get these permissions, the app name here is 'Clare Dev' as shown. just below the title:
<img width="1876" alt="Screenshot 2022-05-06 at 16 57 18" src="https://user-images.githubusercontent.com/7115783/167169352-6e157ec1-9ef7-4c1e-9baa-70e09f2703da.png">

**Comment by RogerSelwyn** [comment]
I hate failing to get things sorted….

**Comment by jdiegmueller** [comment]
> I hate failing to get things sorted….

Well I am blown away, but my permissions request was just granted.  I did have to switch it back to a multitenant app, but once I did that I was good to go with regards to fetching unread mail count & calendar events.

Thanks so much for helping me navigate through this.

**Comment by RogerSelwyn** [comment]
Excellent 😀
