### ISSUE TITLE
AADSTS900971: No reply address provided

### ISSUE THREAD

**Issue by shadow11001** [RogerSelwyn/O365-HomeAssistant#51]
Getting this error, AADSTS900971: No reply address provided, while doing the setup for O365. I have a request url supplied and even tried removing and readding. I also tried the alt auth flow but get the same error.

Any ideas?

**Comment by RogerSelwyn** [comment]
I would suggest you delete the azure app and follow the registration instructions again. In general the alternate auth flow is easier to setup, an upcoming release will change that to the default method.

**Comment by RogerSelwyn** [comment]
This might give you clues - https://stackoverflow.com/questions/66262752/azure-auth-token-aadsts500113-no-reply-address-is-registered-for-the-applicat

**Comment by shadow11001** [comment]
I missed a step for the alt auth lol. Thanks!
