### ISSUE TITLE
New OAUTH2 services in HA

### ISSUE THREAD

**Issue by uSlackr** [RogerSelwyn/O365-HomeAssistant#60]
Just passing this along.  2022.6 has some improved OAUTH2 services per the [release notes](https://rc.home-assistant.io/blog/2022/06/01/release-20226/#streamlining-the-oauth2-experience).  
Maybe this is something you can take advantage of to simplify things for future users.

Thanks for your time commitment on this project.

**Comment by RogerSelwyn** [comment]
Just looking at it some more in other core integrations. For O365 I think it would just provide a new place to store credentials, and I'd then need to link the yaml based config to the UI stored credentials. From what I can see this does handle the authentication, but for the O365 integration this is already handed off to the O365 pypi module which interfaces to MS Graph API.

So I think this would be a fundamental change to the integration authentication logic, for instance using the new OAUTH2 capability you need to provide authorise and token urls, whilst in O365 we provide a redirect uri only.

This may be my lack of understanding of the OAUTH2 methods, and how O365 pypi implements it for MS Graph, but I'm not quite sure that it can improve life.

If you have a different understanding, and can provide a view on how it can be utilised, I'm interested....

**Comment by uSlackr** [comment]
Good info.  As I said - just information in case you hadn't seen it
