### ISSUE TITLE
O365 no longer updating (2022.6)

### ISSUE THREAD

**Issue by GitHubGoody** [RogerSelwyn/O365-HomeAssistant#61]
I updated to 2022.6.6 last night. Now, it seems my O365 integration is broken (sensors and calendar not updating).
```
Logger: homeassistant.components.calendar
Source: helpers/entity_platform.py:724
Integration: Calendar (documentation, issues)
First occurred: June 16, 2022, 6:18:44 PM (938 occurrences)
Last logged: 9:57:46 AM

Updating o365 calendar took longer than the scheduled update interval 0:01:00
```
I've set logger to debug and just restart HA. I'll post more detailed logs later today.

**Comment by GitHubGoody** [comment]
Drats! Despite a few restarts last night, this issue was fixed on the restart from turning on logging. I'll close for now. Sorry ;-)

**Comment by RogerSelwyn** [comment]
Could be just a bad connection for a while. No problem.
