### ISSUE TITLE
Does this work with Hotmail.com accounts?

### ISSUE THREAD

**Issue by alexshte** [RogerSelwyn/O365-HomeAssistant#62]
Hello, apologies if this is not the right place. New to HA and add-ins. Does this work with @hotmail.com accounts to reed calendars, send email, etc? I was not sure since the title is O365. Thank you.-

BTW, configured it with O365 account and love it!

**Comment by RogerSelwyn** [comment]
I would be extremely surprised, your test would be to follow the Azure Apps link in the instructions. It’s possible they host it on O365, but I doubt it provides the same facilities.
