### ISSUE TITLE
New Calendar ID's in o365_calendars_<>.yaml

### ISSUE THREAD

**Issue by GitHubGoody** [RogerSelwyn/O365-HomeAssistant#63]
In the last 1-2 days, the two O365 calendars in my o365_calendars_<>.yaml file were somehow recreated with new cal_id's alongside the two already existing calendars. HA seemed to prefer these new calendars over the two existing. I probably would not have noticed except that it defaulted both of the new calendars to `end_offset: 24` and I was set to 336. I commented out the previously existing calendars, reset `end_offset` and restarted HA. Everything is working again now, but any idea why this might have happened...bug?

**Comment by GitHubGoody** [comment]
Very strange. It just did it again. This was after a restart from updating to 2022.6.7. I took the same steps to correct it and the calendars are back again.

**Comment by RogerSelwyn** [comment]
Have you compared the calendars ids. I doubt they have changed. I’m off on holiday for three weeks, so won’t get looked at until after that.

**Comment by GitHubGoody** [comment]
Yes, the last 9 characters in the string are different. Have a great rest-of-your-vacation!

**Comment by RogerSelwyn** [comment]
Just trying to provide some thoughts on this. The calendar IDs are not something that the HA integration generates, they are handed from the o365 python module (https://github.com/O365/python-o365) and I think they are just from what the MS Graph API is providing. I'll try and do some digging as to why it might happen, but I don't think it is caused by new authentication or anything like that. I've done many authentications in my dev environment, and the yaml file doesn't change. I can see no reason why a HA update should trigger it.

**Comment by GitHubGoody** [comment]
I'm not sure why it's happening, but it keeps happening. Here's my o365_calendars_<account>.yaml file after three of these occurences:

![O365CalendarIDs](https://user-images.githubusercontent.com/46235745/178574563-5957da45-256a-4634-9b45-ca3b5e7532a8.PNG)

**Comment by RogerSelwyn** [comment]
Doing a bit of Googling it looks like some people had problems at the start of last year. But with over 1200 installs and no other complaints, my suspicion is it is unique to your environment (or else no-one else does any config - i do by the way). But don't despair, I'll continue to chew over it.

**Comment by RogerSelwyn** [comment]
I've done some more looking and can see no reason why this is happening. If it was happening to lots of people, then it might be easier to track what the cause is.

**Comment by GitHubGoody** [comment]
Not sure. It kept happening, so I just deleted the integration and everything on the Microsoft side, then started over and it's been working without dupes for a couple weeks now. We can probably close this one and just re-open if it happens again.

**Comment by RogerSelwyn** [comment]
Cool
