### ISSUE TITLE
Color appearance in HA?

### ISSUE THREAD

**Issue by edgeform** [RogerSelwyn/O365-HomeAssistant#64]
Is there a way to specify the color of each calendar in HA? Didn't see anything like that peeking at the code.

Not a huge deal, and it might be something I need to set in HA - I'm an admitted novice with it currently.

**Comment by uSlackr** [comment]
Here's an interesting work-around:
https://community.home-assistant.io/t/google-calendar-color/278352/3
I verified it works with O365

**Comment by edgeform** [comment]
Figured that it was a HA issue, and not with this specific project.

Bummer that HA doesn't offer this functionality. I may be able to make fake, invisible calendars in the calendar configuration yaml to skip colors in the hard-coded order.

Appreciate the response!

**Comment by uSlackr** [comment]
I am seeing duplicate calendar names, but no entries associated with the dupes.  Odd

**Comment by edgeform** [comment]
It looks like if `track: false` is set, HA completely ignores it even in the color order. Bummer!
