### ISSUE TITLE
Automation Not Starting when new calendar is created

### ISSUE THREAD

**Issue by WimTh** [RogerSelwyn/O365-HomeAssistant#72]
We are trying to trigger a switch when there is a new calendar event created.
But for some reason the autmation does not work straight away.
It looks like there is a 15 min delay before the automation is starting?

**Comment by RogerSelwyn** [comment]
What version of the integration are you using? This is a pill based integration, not push, which means it is based on polling. I think I increased the polling frequency in a fairly recent release but I don’t remember off the top of my head what that frequency is.

**Comment by RogerSelwyn** [comment]
Change was made in v3.0.0 released in April. Polling is now based on HA default, I'm not sure what that is

**Comment by WimTh** [comment]
Your comment put me on the right track.
It was not the polling interval...
But it was the automation mode, I switched it to **Queued** and now it works perfect.
Thx for the help and the great project.
