### ISSUE TITLE
Configurator-O365

### ISSUE THREAD

**Issue by Daniel100111** [RogerSelwyn/O365-HomeAssistant#73]
Hi there.

I'm getting a noification to link my account after every re-start. Other than that everything is working.

Hav I missed someting?

Thanks for the add-on!

Regards

**Comment by RogerSelwyn** [comment]
Have a look in the logs and see if anything is being reported there.

**Comment by Daniel100111** [comment]
`2022-10-24 20:21:34.560 ERROR (MainThread) [homeassistant.components.sensor] o365: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 493, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 703, in async_device_update
    await task
  File "/config/custom_components/o365/sensor.py", line 271, in async_update
    data = await self.hass.async_add_executor_job(self._teams.get_my_presence)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/O365/teams.py", line 720, in get_my_presence
    response = self.con.get(url)
  File "/usr/local/lib/python3.10/site-packages/O365/connection.py", line 847, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/O365/connection.py", line 836, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/O365/connection.py", line 798, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None`

**Comment by RogerSelwyn** [comment]
Please post your config redacting any secrets.

**Comment by RogerSelwyn** [comment]
Also when posting it please use the smaller than greater than in the GitHub editor bar to format it correctly. If you can do that for the log entry as well, it would make it clearer.

**Comment by Daniel100111** [comment]
`o365:
  client_id: "x"
  client_secret: "x"
  alt_auth_method: False
  enable_update: False
  email_sensor:
    - name: inbox
      max_items: 2
      is_unread: True
      download_attachments: False
  query_sensors:
    - name: "Example"
      folder: "Inbox/Test_Inbox" #Default is Inbox
      from: "mail@example.com"
      subject_contains: "Example subject"
      has_attachment: True
      max_items: 2
      is_unread: True
  status_sensors: # Cannot be used for personal accounts
    - name: "User Teams Status"
  chat_sensors: # Cannot be used for personal accounts
    - name: "User Chat"`

**Comment by Daniel100111** [comment]
o365:
  client_id: "x"
  client_secret: "x"
  alt_auth_method: False
  enable_update: False
  email_sensor:
    - name: inbox
      max_items: 2
      is_unread: True
      download_attachments: False
  query_sensors:
    - name: "Example"
      folder: "Inbox/Test_Inbox" #Default is Inbox
      from: "mail@example.com"
      subject_contains: "Example subject"
      has_attachment: True
      max_items: 2
      is_unread: True
  status_sensors: # Cannot be used for personal accounts
    - name: "User Teams Status"
  chat_sensors: # Cannot be used for personal accounts
    - name: "User Chat"

**Comment by RogerSelwyn** [comment]
Please repost formatted correctly. Should show like this. Without this it isn't possible to see if it is formatted correctly.

```
o365:
  accounts:
    - account_name: roger
      client_secret: !secret o365_secret
      client_id: !secret o365_id
      alt_auth_method: False
```

**Comment by Daniel100111** [comment]
- cal_id: X
  entities:
  - device_id: o365 Essies Calendar
    end_offset: 24
    name: Calendar
    start_offset: 0
    track: true

**Comment by RogerSelwyn** [comment]
Please, please just post using the GitHub formatting icon in the toolbar. Please post log, config.yaml no o365_configuration.yaml.

**Comment by RogerSelwyn** [comment]
To be honest, I would cut the config back to the basic, as I've shown above. Prove that works before you add any other sensors.

**Comment by Daniel100111** [comment]
Changed the config to basic and not get a request to reconnect.

**Comment by RogerSelwyn** [comment]
Ok, so build up from there. It could be you don't have permission for everything you are asking for. Note the comments in the example config about personal accounts. If you try to setup something which your O365 won't allow, you will get a security prompt every time.

**Comment by Daniel100111** [comment]
Cool - Thank you for your help.

**Comment by Daniel100111** [comment]
a Bit off topic but do you maybe have a card for the frontend to create a calander entry?

**Comment by RogerSelwyn** [comment]
Sorry, I don’t have one but I use Atomic Calendar Revive available via HACS
