### ISSUE TITLE
Is it possible to get this to work Microsoft To Do?

### ISSUE THREAD

**Issue by JazzMan808** [RogerSelwyn/O365-HomeAssistant#78]
There was a previous HA addon which enabled To Do tasks to be pulled into HA
https://github.com/black-roland/homeassistant-microsoft-todo

could it be integrated into this addon?

**Comment by RogerSelwyn** [comment]
It looks like retrieval of tasks might be possible. I'll have a chew on it. car problems to solve now.

**Comment by RogerSelwyn** [comment]
I've had a quick look at the code. It's probably possible to get this working relatively simply. 

I note it exposes as a calendar currently, but with no calendar functionality. I guess the intent might have been to have items that have a due and reminder time appear on the calendar in the future. To be honest in my view that is over the top for a task list (and would be quite a lot more work to implement).

I'd suggest having a configuration option which turns on tasks, and then expose them as standard sensors, with the data much as it is now.

**Comment by RogerSelwyn** [comment]
Unfortunately I have come to a full stop on this, because the ToDo api is only supported under the MS Office api via the [O365 Python module](https://pypi.org/project/O365/}, and the integration currently uses the MS Graph api. I'll have to see what work it is to get is added to that module.

**Comment by RogerSelwyn** [comment]
OK, so I've looked at the O365 Module and the practicality of submitting a PR to it. It looks like a major re-write to the tasks/ToDo classes in there. To be honest it would be far simpler to get the @black-roland integration working.

**Comment by RogerSelwyn** [comment]
@JazzMan808 I could do with a view here.

I've written a fair amount of a Pull Request to the underlying O365 module to add the MS Graph functionality to support getting the tasks. This is basic at the moment, it just retrieves the top level task lists and the completed tasks on them. I note that the black-roland integration returns all_tasks and overdue_tasks. I haven't handled overdue yet, but that will be simple to add.

Via the MS Office 365 the O365 module had fairly full functionality across tasks lists and items, including creating new lists and items, plus modify/delete.

I'm interested to know what is important. i.e. The black-roland supports displaying lists and creating a new item on a list. Is that enough or is there a strong desire for more functionality?

**Comment by RogerSelwyn** [comment]
Also, at the moment it only gets uncompleted tasks and it will do it for all available lists. Is there a need for completed tasks, or a method to reduce which lists are shown?

**Comment by JazzMan808** [comment]
Hi @RogerSelwyn 

sorry for not getting back to you sooner work and kids, leaves no time to play. 

Firstly hope you got over your car troubles and many thanks for looking into this. 

Are completed tasks required? No
It would just be task and due date. 

for now a simple retrieval of tasks is required no need to create new via API

**Comment by RogerSelwyn** [comment]
PR raised here - https://github.com/O365/python-o365/pull/874
