### ISSUE TITLE
After install via HACS no Office 365 Integration

### ISSUE THREAD

**Issue by ShlomiPorush** [RogerSelwyn/O365-HomeAssistant#8]
Just install it via HACS & restart a number of times still no Office 365 Integration can be found in the list

**Comment by IceBotYT** [comment]
I am having the same behavior

**Comment by IceBotYT** [comment]
Ah, just realized [you have to manually configure it in `configuration.yaml`.](https://github.com/RogerSelwyn/O365-HomeAssistant#configuration)

**Comment by ShlomiPorush** [comment]
Manual Configuration works..

**Comment by IceBotYT** [comment]
Close the issue please
