### ISSUE TITLE
nabu casa url support?

### ISSUE THREAD

**Issue by uSlackr** [RogerSelwyn/O365-HomeAssistant#9]
I'm unclear on what uri to register with Azure.  Do/Can I use the nabu casa external URL?  (I don't have it exposed otherwise).  Or do I use my internal URL?

My second question is on the cal_id field.  It says O365 generated.  Where do I find it?

Thanks so much for picking this support up.

**Comment by uSlackr** [comment]
I just found this:  https://github.com/RogerSelwyn/O365-HomeAssistant/issues/5

I'm trying the nabu casa address

**Comment by uSlackr** [comment]
the nabu casa url (with /api/o365 appended) worked.  I've been successful in sending email.

I have calendar entries.  I changed the cal_id to "Calendar" and it worked, but I suspect anything might work

**Comment by RogerSelwyn** [comment]
Hi - for some reason I didn't get notifications of the items you raised. Thanks for the PR. Are you now working ok?

**Comment by RogerSelwyn** [comment]
fyi - the cal_id is a very long alphanumeric. I think it is automatically created and put in 0365_calendars.yaml. I did it so long ago that I forget how it worked but I'm pretty sure it is created automatically, then you can tweak the config in it. The instructions previously created say do not change.

https://github.com/RogerSelwyn/O365-HomeAssistant#example-o365_calendaryaml

**Comment by uSlackr** [comment]
> Hi - for some reason I didn't get notifications of the items you raised. Thanks for the PR. Are you now working ok?
Working, great - thanks.  Now I need to learn how to make alerts from calendar items.

I do have the info in my o365_calendars.yaml.  I thought I had to create that.  Thanks!
