### ISSUE TITLE
Error after updating from 3.3.1 to 4.0.1

### ISSUE THREAD

**Issue by derhappy** [RogerSelwyn/O365-HomeAssistant#92]
After holding back for quite some time because of this alt_auth change and already expecting it to not work anymore, I finally tried to update the component.
Unfortunately my expectations where met by greeting me with the error posted below.
Any idea what's happening?

I'm running supervised, not available from the internet. Before the update it was running fine with alt_auth_flow: True.

```
Logger: homeassistant.setup
Source: custom_components/o365/__init__.py:120
Integration: Office 365 Calendar ([documentation](https://github.com/RogerSelwyn/O365-HomeAssistant), [issues](https://github.com/RogerSelwyn/O365-HomeAssistant/issues))
First occurred: 17:23:58 (1 occurrences)
Last logged: 17:23:58
Error during setup of component o365

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/o365/__init__.py", line 72, in async_setup
    _write_out_config(hass, accounts)
  File "/config/custom_components/o365/__init__.py", line 120, in _write_out_config
    with open(yaml_filepath, "w", encoding="UTF8") as out:
FileNotFoundError: [Errno 2] No such file or directory: '/config/o365_storage/o365_converted_configuration.yaml'
```

Config:
```
o365:
  client_secret: "some-glibberish"
  client_id: "some-random-characters"
#  alt_auth_flow: True
  alt_auth_method: True
```

**Comment by derhappy** [comment]
I went back to 3.3.0 with the config unchanged and it's working again. So it's nothing about the auth.

**Comment by RogerSelwyn** [comment]
Nope, I'm about to post the fix. By the way if you had alt_auth_flow True, then you should have alt_auth_method should be False.

**Comment by derhappy** [comment]
yea, I started like that about the auth, but switched it to true because of the error. I'll change it back to false before trying you fix, just to be sure.

**Comment by derhappy** [comment]
I took over your code, it's working now. Thanks a lot for your quick help!
