### ISSUE TITLE
Tasks - Due to show Date only

### ISSUE THREAD

**Issue by JazzMan808** [RogerSelwyn/O365-HomeAssistant#93]
Hi Roger,

Hope your well? Quick feedback when creating a task, Microsoft To Do only allows you to have a date as due, but when imported into home assistant the due date is populated with T00:00:00+00:00 at the end

is it possible to stop this from being populated in the sensor?

![image](https://user-images.githubusercontent.com/83962692/206318162-3054dcdd-a134-4bf0-97fb-47ed8656febf.png)

![image](https://user-images.githubusercontent.com/83962692/206318218-0e66675c-9def-4f8e-89b2-b44758dd5188.png)

**Comment by JazzMan808** [comment]
Hi Roger

Thanks for getting back to me

I will check various interfaces but so I’ve tried on iOS chrome and iOS todo app - neither of which allow for a due date time only date. 

I have some android devices at home and will check that later also.

**Comment by RogerSelwyn** [comment]
Just looking at the api again. If I remember, I couldn't get the Graph API to take a time on due date, but it would on reminder date/time. When I look at tasks created via iOS reminder app and via the integration (where I wrote the interface to the O365 API), when created via iOS is sets due date & time the same as reminder date & time. Whilst via the api, I can't set time on due date. I need to give it another go at some point.

**Comment by RogerSelwyn** [comment]
Just created a task direct on the graph api, and even though the field is called dueDateTime and takes a datetime value, it only populates the date (with a 00:00 time) into the created task. However if I create via iOS app it populates both date and time. Strange.

**Comment by JazzMan808** [comment]
Hi Roger are Reminders and Due two separate things?

When selected a due date it is date only (see image 1)
![image](https://user-images.githubusercontent.com/83962692/206417428-22958ad1-a3a7-4e80-9a24-6591cfec005c.png)

but when selecting a reminder you do have the option of date & time - but the tool doesn't show reminders? its only the Subject and Due
![image](https://user-images.githubusercontent.com/83962692/206417567-f2774934-b164-423b-ac25-4d935e324150.png)

I have created a task "Test8" which has a due and reminder assigned but Home Assistant only pulls the Subject and Due fields
![image](https://user-images.githubusercontent.com/83962692/206419174-08d4a062-c178-450d-b85c-7bc91d82f702.png)
![image](https://user-images.githubusercontent.com/83962692/206419240-2a6dd3b9-efd9-4d91-a342-4484460a9cae.png)

**Comment by RogerSelwyn** [comment]
Please re-look at my first screenshot where you can see the reminder being set, (this also sets due datetime), and the output in HA. This is reached by clicking on the 'i' icon.

I set one item in the iOS reminders app, which generated two fields due and reminder with the same values. Only due is shown in HA currently, but reminder could be added. 

It's not clear to me what app you are using to create items. For me it is this app.
![IMG_0334](https://user-images.githubusercontent.com/7115783/206437027-deebc7bf-831b-412d-a7a1-f95ad83fcc00.jpeg)

**Comment by JazzMan808** [comment]
Hi Roger

I was using the actual Microsoft To Do application on IOS and the To Do Web application from office.com , rather than the native iOS reminder app but I can see your point now that the iOS Reminders app does allow for time.

**Comment by RogerSelwyn** [comment]
I'm going to add reminder output as well. 

It shows how inconsistent everything is. If I create a task in Mac MS Outlook with a reminder, then the reminder is set to the time I set, and the due date is set with a time as 1 minute before midday.

**Outlook**
```
            "dueDateTime": {
                "dateTime": "2022-12-09T11:59:00.0000000",
                "timeZone": "UTC"
            },
            "reminderDateTime": {
                "dateTime": "2022-12-09T08:00:00.0000000",
                "timeZone": "UTC"
```
**iOS reminders**
```
            "dueDateTime": {
                "dateTime": "2022-12-09T09:00:00.0000000",
                "timeZone": "UTC"
            },
            "reminderDateTime": {
                "dateTime": "2022-12-09T09:00:00.0000000",
                "timeZone": "UTC"
            }
```
So since I'm guessing it is driven in reality by the reminder field, so I'll shorten due to date only

**Comment by JazzMan808** [comment]
Thanks Roger - aligned with the approach!

**Comment by RogerSelwyn** [comment]
Do you agree that an overdue task is one where the due date is yesterday (or before) as opposed to today?

**Comment by JazzMan808** [comment]
Yes agreed overdue should be before the due date (in the past). 
still might be able to make the due date if it is due today 😃

**Comment by RogerSelwyn** [comment]
Fixed by - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.0.3
