### ISSUE TITLE
Cannot use personal account

### ISSUE THREAD

**Issue by P-Stenbumling** [RogerSelwyn/O365-HomeAssistant#95]
Hi!

i get the following when trying to link:  
"You can't sign in here with a personal account. Use your work or school account instead."

**Comment by RogerSelwyn** [comment]
Sorry, you need to provide more detail than that. Have you configured your azure application as specified - please double check? Are you using the same email address you set up the azure application? I'd anticipate that the error is correct, in that you are logged in with a personal account and not the azure hosted account, it is possible (I have both a personal and an O365 account both with the same email address - it can be confusing).

**Comment by P-Stenbumling** [comment]
ive tested in my directory called "default directory" and one in called "Default directory" no luck 
" in that you are logged in with a personal account and not the azure hosted account,"
how can i check this, its realy confusing  im logging in with my outlook.com account and the domain turns to <name>outlook.onmicrosoft.com

**Comment by P-Stenbumling** [comment]
i found this statement now....
Due to temporary differences in supported functionality, we don't recommend enabling personal Microsoft accounts for an existing registration. If you need to enable personal accounts, you can do so using the manifest editor.  [Learn more about these restrictions.​](https://go.microsoft.com/fwlink/?linkid=2107401)

**Comment by RogerSelwyn** [comment]
Not sure what you mean about directories. With regards the account, log out on your browser, make sure you are logged out, then log in again. If you have two accounts with the same email address it will prompt you to login with the right account.

When you created the app, did you make sure to use this permission - `Accounts in any organizational directory (Any Azure AD directory - Multitenant) and personal Microsoft accounts (e.g. Skype, Xbox)`?

**Comment by P-Stenbumling** [comment]
I've manged it to work!
but i still got an error where i cant remove my notifications from previous attempts
"failed to call service persistent_notification/dismiss. required key not provided @ data['notification_id']
any tips here?
![image](https://user-images.githubusercontent.com/39261692/206773501-ef11e955-b360-41dc-b30c-e7c660ded28e.png)

**Comment by P-Stenbumling** [comment]
gone!
no issues

**Comment by RogerSelwyn** [comment]
That's a new one on me, I'll take a look because I've noticed the window has stopped closing. After a reboot I'd just refresh my browser, since HA doesn't retain notifications between reboots.
