### ISSUE TITLE
Task services

### ISSUE THREAD

**Issue by P-Stenbumling** [RogerSelwyn/O365-HomeAssistant#97]
i can see thats a service for new_task, missing some parts? 
tried to att entity_id but didn't manage it to work.
how about update/delete a task?
Br
![image](https://user-images.githubusercontent.com/39261692/206779888-8bb73e03-3d0c-4d2f-be8c-d5185f816479.png)

**Comment by RogerSelwyn** [comment]
Please post error from the logs. There is no update/delete provided since this matched functionality from an implementation in a separate integration.

**Comment by P-Stenbumling** [comment]
added entity_id and it  worked now. not provided in the "fill example data" and its not documented. 
"There is no update/delete provided since this matched functionality from an implementation in a separate integration."
What Integrations brings that capabilites? 
so the other integration doesn't have add but has update/delete or what?

**Comment by RogerSelwyn** [comment]
> added entity_id and it worked now. not provided in the "fill example data" and its not documented.

No, that is how HA works and I can't change it. But if you go to UI mode it will provide you a selector to select an appropriate entity. Feel free to write a change to the documentation available on my GitHub.

> "There is no update/delete provided since this matched functionality from an implementation in a separate integration."
> What Integrations brings that capabilites?
> so the other integration doesn't have add but has update/delete or what?

I was requested to replicate the functionality of an integration that was no longer supported and not working. That integration only provided add. I don't know of any that provide update and delete.

**Comment by P-Stenbumling** [comment]
Ok thanks, any chance of adding that functionality? 
https://learn.microsoft.com/en-us/graph/api/todotask-update?view=graph-rest-1.0&tabs=http
https://learn.microsoft.com/en-us/graph/api/todotask-delete?view=graph-rest-1.0&tabs=http

**Comment by RogerSelwyn** [comment]
Included with - https://github.com/RogerSelwyn/O365-HomeAssistant/releases/tag/v4.0.4
