### ISSUE TITLE
Migration issue: o365_storage folder is not being created

### ISSUE THREAD

**Issue by mplogas** [RogerSelwyn/O365-HomeAssistant#99]
Upgraded from 3.x to 4.0.3 a few days ago and my calendar integration stopped working. I received the repair notice, which suggested an alternative configuration is placed into the o365_storage folder. That folder was not created and therefore no alternative configuration. I created the folder myself (under the config folder) and rebooted but it didn't create the config file.

I have one error message in my log files:
```
Logger: homeassistant.setup
Source: custom_components/o365/__init__.py:70
Integration: o365 ([documentation](https://github.com/RogerSelwyn/O365-HomeAssistant), [issues](https://github.com/RogerSelwyn/O365-HomeAssistant/issues))
First occurred: 13:55:46 (1 occurrences)
Last logged: 13:55:46

Error during setup of component o365
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 253, in _async_setup_component
    result = await task
  File "/config/custom_components/o365/__init__.py", line 70, in async_setup
    accounts = [LEGACY_SCHEMA(conf)]
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: extra keys not allowed @ data['alt_auth_flow']
```

my o365 config

```yaml
o365:
  client_secret: !secret o365_clientsecret
  client_id: !secret o365_appid
  alt_auth_flow: true
```

Will downgrade again for now. but would like to upgrade/migrate.

**Comment by RogerSelwyn** [comment]
Read the information on alt_auth_flow. Use alt_auth_method instead with a reverse value.

Would be useful to have any log from when it failed after upgrade.

**Comment by RogerSelwyn** [comment]
https://rogerselwyn.github.io/O365-HomeAssistant/authentication.html

**Comment by mplogas** [comment]
> https://rogerselwyn.github.io/O365-HomeAssistant/authentication.html - noted as a breaking change in 4.0.1

Apologies, it seems I missed this one as I skipped 4.0.1 and went directly to 4.0.3. 
With ```alt_auth_flow``` removed, the folder and the new config files are being created and I can continue migrating. Thank you so much for your swift help!
